"""
Tests for UC-010 locally-generated images in the Encrypted Knowledge Bank
(ADR-033 — DORMANT build).

Covers the Module C storage contract for ``generated_images``:
  * ``store_generated_image`` / ``get_generated_image`` round-trip.
  * at-rest encryption: prompt + data are ciphertext on disk; mime is a
    plaintext label.
  * AAD binding: a row re-associated to a DIFFERENT session must refuse to
    decrypt (quarantined → None), never partial plaintext.
  * DELETE-on-discard: ``delete_generated_image`` reaps the row outright +
    is idempotent.
  * keyed-hash dedup index over bytes (same bytes → same index).
  * THE NO-VLM STRUCTURAL LOCK: generated bytes never reach the embedder.

Reuses the deterministic stub-embedder fixtures from ``test_knowledge_bank`` so
no ONNX model is required (worktree-safe).
"""

from __future__ import annotations

import uuid
from pathlib import Path

import pytest

from services.assistant_orchestrator.src.knowledge_bank import (
    EncryptedKnowledgeBank,
    GeneratedImage,
    GeneratedImageMeta,
    KnowledgeBankError,
    _guard_embed_input,
)
from services.assistant_orchestrator.tests.test_knowledge_bank import (
    _make_bank,
    _make_cipher,
)

_PNG = b"\x89PNG\r\n\x1a\n" + b"\x00\x01\x02\x03" * 64
_JPEG = b"\xff\xd8\xff\xe0" + b"\x10\x20\x30\x40" * 64


@pytest.fixture()
def bank() -> EncryptedKnowledgeBank:
    b = _make_bank()
    yield b
    b.close()


# ---------------------------------------------------------------------------
# Round-trip + encryption
# ---------------------------------------------------------------------------


def test_store_get_round_trip(bank: EncryptedKnowledgeBank) -> None:
    iid = uuid.uuid4().hex
    bank.store_generated_image(
        image_id=iid, session_id="s1", image_bytes=_PNG,
        mime="image/png", prompt="a red cube on a table",
    )
    got = bank.get_generated_image(iid)
    assert got is not None
    assert got.image_id == iid
    assert got.session_id == "s1"
    assert got.mime == "image/png"
    assert got.prompt == "a red cube on a table"
    assert got.data == _PNG


def test_get_unknown_returns_none(bank: EncryptedKnowledgeBank) -> None:
    assert bank.get_generated_image("c" * 32) is None


def test_prompt_and_data_encrypted_at_rest(tmp_path: Path) -> None:
    db = str(tmp_path / "knowledge.db")
    b = _make_bank(db_path=db)
    iid = uuid.uuid4().hex
    b.store_generated_image(
        image_id=iid, session_id="s1", image_bytes=_PNG,
        mime="image/png", prompt="SECRET-PROMPT-MARKER",
    )
    b.close()
    blob = Path(db).read_bytes()
    # Prompt plaintext + image bytes must NOT appear on disk; mime label does.
    assert b"SECRET-PROMPT-MARKER" not in blob
    assert _PNG not in blob
    assert b"image/png" in blob


def test_session_aad_binding_quarantines(bank: EncryptedKnowledgeBank) -> None:
    """A row whose plaintext session_id is rewritten must refuse to decrypt under
    the tampered session — quarantined to None (AAD binds session_id|image_id)."""
    from shared.security.field_cipher import FieldCipherError

    iid = uuid.uuid4().hex
    bank.store_generated_image(
        image_id=iid, session_id="real-session", image_bytes=_PNG,
        mime="image/png", prompt="x",
    )
    # Tamper: rewrite the plaintext session_id column to a different session.
    with bank._conn:
        bank._conn.execute(
            "UPDATE generated_images SET session_id=? WHERE image_id=?",
            ("attacker-session", iid),
        )
    # The direct field decrypt under the tampered session must refuse.
    raw = bank._conn.execute(
        "SELECT data FROM generated_images WHERE image_id=?", (iid,)
    ).fetchone()[0]
    with pytest.raises(FieldCipherError):
        bank._dec_generated_field("data", "attacker-session", iid, raw)
    # And the read-by-id quarantines (returns None — never partial plaintext).
    assert bank.get_generated_image(iid) is None


def test_wrong_image_id_aad_refuses(bank: EncryptedKnowledgeBank) -> None:
    from shared.security.field_cipher import FieldCipherError

    a, b_id = uuid.uuid4().hex, uuid.uuid4().hex
    bank.store_generated_image(
        image_id=a, session_id="s1", image_bytes=_PNG, mime="image/png", prompt="a",
    )
    raw_a = bank._conn.execute(
        "SELECT data FROM generated_images WHERE image_id=?", (a,)
    ).fetchone()[0]
    # a's blob under b's image_id must fail authentication.
    with pytest.raises(FieldCipherError):
        bank._dec_generated_field("data", "s1", b_id, raw_a)


# ---------------------------------------------------------------------------
# DELETE-on-discard
# ---------------------------------------------------------------------------


def test_delete_on_discard(bank: EncryptedKnowledgeBank) -> None:
    iid = uuid.uuid4().hex
    bank.store_generated_image(
        image_id=iid, session_id="s1", image_bytes=_PNG, mime="image/png", prompt="x",
    )
    assert bank.generated_image_count("s1") == 1
    assert bank.delete_generated_image(iid) is True
    assert bank.get_generated_image(iid) is None
    assert bank.generated_image_count("s1") == 0
    # Idempotent: deleting an absent id is False, not an error.
    assert bank.delete_generated_image(iid) is False


def test_delete_empty_id_is_false(bank: EncryptedKnowledgeBank) -> None:
    assert bank.delete_generated_image("") is False


# ---------------------------------------------------------------------------
# Dedup index + validation
# ---------------------------------------------------------------------------


def test_same_bytes_same_hash(bank: EncryptedKnowledgeBank) -> None:
    a, b_id = uuid.uuid4().hex, uuid.uuid4().hex
    bank.store_generated_image(
        image_id=a, session_id="s1", image_bytes=_PNG, mime="image/png", prompt="a",
    )
    bank.store_generated_image(
        image_id=b_id, session_id="s2", image_bytes=_PNG, mime="image/png", prompt="b",
    )
    ha = bank._conn.execute(
        "SELECT image_hash FROM generated_images WHERE image_id=?", (a,)
    ).fetchone()[0]
    hb = bank._conn.execute(
        "SELECT image_hash FROM generated_images WHERE image_id=?", (b_id,)
    ).fetchone()[0]
    assert bytes(ha) == bytes(hb)  # identical bytes → identical keyed index


def test_store_rejects_empty_fields(bank: EncryptedKnowledgeBank) -> None:
    with pytest.raises(KnowledgeBankError):
        bank.store_generated_image(
            image_id="", session_id="s1", image_bytes=_PNG, mime="image/png", prompt="x",
        )
    with pytest.raises(KnowledgeBankError):
        bank.store_generated_image(
            image_id=uuid.uuid4().hex, session_id="", image_bytes=_PNG,
            mime="image/png", prompt="x",
        )
    with pytest.raises(KnowledgeBankError):
        bank.store_generated_image(
            image_id=uuid.uuid4().hex, session_id="s1", image_bytes=b"",
            mime="image/png", prompt="x",
        )
    with pytest.raises(KnowledgeBankError):
        bank.store_generated_image(
            image_id=uuid.uuid4().hex, session_id="s1", image_bytes=_PNG,
            mime="", prompt="x",
        )


# ---------------------------------------------------------------------------
# No-VLM structural lock — generated bytes never reach the embedder
# ---------------------------------------------------------------------------


def test_generated_bytes_never_embedded() -> None:
    """The embed guard refuses non-str — generated image bytes can never reach
    the embedder even by a future wiring mistake."""
    with pytest.raises(TypeError):
        _guard_embed_input([_PNG])
    with pytest.raises(TypeError):
        _guard_embed_input(_JPEG)  # not even a list


def test_retrieve_never_surfaces_generated_image(bank: EncryptedKnowledgeBank) -> None:
    """retrieve() is text-only — a generated image is never a hit."""
    iid = uuid.uuid4().hex
    bank.store_generated_image(
        image_id=iid, session_id="s1", image_bytes=_PNG,
        mime="image/png", prompt="a red cube",
    )
    hits = bank.retrieve("red cube")
    # No hit carries the generated image id or its bytes (retrieve reads chunks).
    assert all(getattr(h, "doc_uuid", "") != iid for h in hits)


# ---------------------------------------------------------------------------
# UC-010 Phase 1 (#667): list metadata-only + saved flag + mark-saved + migration
# ---------------------------------------------------------------------------


def test_list_generated_images_metadata_only(bank: EncryptedKnowledgeBank) -> None:
    """list_generated_images returns cheap METADATA (no prompt, no bytes) and the
    saved flag — newest first.  The NamedTuple has no prompt/data field at all."""
    a, b_id = uuid.uuid4().hex, uuid.uuid4().hex
    bank.store_generated_image(
        image_id=a, session_id="s1", image_bytes=_PNG, mime="image/png",
        prompt="SECRET-PROMPT-A",
    )
    bank.store_generated_image(
        image_id=b_id, session_id="s2", image_bytes=_JPEG, mime="image/jpeg",
        prompt="SECRET-PROMPT-B",
    )
    metas = bank.list_generated_images()
    assert len(metas) == 2
    assert all(isinstance(m, GeneratedImageMeta) for m in metas)
    # METADATA ONLY: the record type carries no prompt and no bytes field.
    assert not hasattr(metas[0], "prompt")
    assert not hasattr(metas[0], "data")
    # Newest first (b stored after a).
    ids = [m.image_id for m in metas]
    assert ids == [b_id, a]
    by_id = {m.image_id: m for m in metas}
    assert by_id[a].session_id == "s1"
    assert by_id[a].mime == "image/png"
    assert by_id[a].saved is False  # never saved yet
    assert by_id[a].byte_size > 0  # length(data) ciphertext size, not a decrypt
    assert by_id[b_id].mime == "image/jpeg"


def test_list_generated_images_does_not_decrypt(
    bank: EncryptedKnowledgeBank, monkeypatch
) -> None:
    """Building the listing must NEVER call the field cipher's decrypt — the list
    is metadata-only by construction.  Patch the bank's decrypt to explode and
    assert list still works (a decrypt would blow up the test)."""
    iid = uuid.uuid4().hex
    bank.store_generated_image(
        image_id=iid, session_id="s1", image_bytes=_PNG, mime="image/png",
        prompt="SECRET",
    )

    def _boom(*_a, **_k):  # pragma: no cover — must never be reached by list
        raise AssertionError("list_generated_images must not decrypt anything")

    monkeypatch.setattr(bank._cipher, "decrypt", _boom)
    metas = bank.list_generated_images()
    assert len(metas) == 1
    assert metas[0].image_id == iid


def test_list_generated_images_session_filter(bank: EncryptedKnowledgeBank) -> None:
    a, b_id = uuid.uuid4().hex, uuid.uuid4().hex
    bank.store_generated_image(
        image_id=a, session_id="s1", image_bytes=_PNG, mime="image/png", prompt="a",
    )
    bank.store_generated_image(
        image_id=b_id, session_id="s2", image_bytes=_PNG, mime="image/png", prompt="b",
    )
    only_s1 = bank.list_generated_images("s1")
    assert [m.image_id for m in only_s1] == [a]
    assert bank.list_generated_images("nope") == []


def test_list_generated_images_empty(bank: EncryptedKnowledgeBank) -> None:
    assert bank.list_generated_images() == []


def test_mark_generated_image_saved_flips_flag(bank: EncryptedKnowledgeBank) -> None:
    iid = uuid.uuid4().hex
    bank.store_generated_image(
        image_id=iid, session_id="s1", image_bytes=_PNG, mime="image/png", prompt="x",
    )
    assert bank.list_generated_images()[0].saved is False
    assert bank.mark_generated_image_saved(iid) is True
    assert bank.list_generated_images()[0].saved is True
    # Idempotent: marking an already-saved image is a no-op success.
    assert bank.mark_generated_image_saved(iid) is True
    assert bank.list_generated_images()[0].saved is True
    # The flag flip touches no encrypted column — the image still decrypts.
    got = bank.get_generated_image(iid)
    assert got is not None and got.data == _PNG and got.prompt == "x"


def test_mark_saved_unknown_and_empty_id(bank: EncryptedKnowledgeBank) -> None:
    assert bank.mark_generated_image_saved("a" * 32) is False  # unknown id
    assert bank.mark_generated_image_saved("") is False  # empty id


def test_delete_clears_from_listing(bank: EncryptedKnowledgeBank) -> None:
    iid = uuid.uuid4().hex
    bank.store_generated_image(
        image_id=iid, session_id="s1", image_bytes=_PNG, mime="image/png", prompt="x",
    )
    assert len(bank.list_generated_images()) == 1
    assert bank.delete_generated_image(iid) is True
    assert bank.list_generated_images() == []


def test_saved_migration_adds_column_to_pre_existing_table(tmp_path: Path) -> None:
    """A store created WITHOUT the saved column (an older build) gains it on the
    next open via the idempotent ALTER-TABLE migration; existing rows migrate to
    not-saved (past /saves are not retroactively known)."""
    import sqlite3

    db = str(tmp_path / "legacy_knowledge.db")
    cipher = _make_cipher()

    # 1. Build a store, then SIMULATE the pre-#667 schema by dropping the saved
    #    column (SQLite has no DROP COLUMN on old versions, so rebuild the table
    #    in the OLD shape with a row in it, then reopen via EncryptedKnowledgeBank).
    b = _make_bank(db_path=db, cipher=cipher)
    iid = uuid.uuid4().hex
    b.store_generated_image(
        image_id=iid, session_id="s1", image_bytes=_PNG, mime="image/png", prompt="x",
    )
    b.close()

    # Recreate generated_images WITHOUT the saved column, preserving the row.
    raw = sqlite3.connect(db)
    cols = [r[1] for r in raw.execute("PRAGMA table_info(generated_images)").fetchall()]
    assert "saved" in cols, "fresh build should already have the column"
    raw.executescript(
        """
        ALTER TABLE generated_images RENAME TO _gi_new;
        CREATE TABLE generated_images (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            image_id TEXT NOT NULL UNIQUE,
            session_id TEXT NOT NULL,
            image_hash BLOB NOT NULL,
            mime TEXT NOT NULL,
            prompt BLOB NOT NULL,
            data BLOB NOT NULL,
            created_at TEXT NOT NULL
        );
        INSERT INTO generated_images
            (id, image_id, session_id, image_hash, mime, prompt, data, created_at)
        SELECT id, image_id, session_id, image_hash, mime, prompt, data, created_at
        FROM _gi_new;
        DROP TABLE _gi_new;
        """
    )
    raw.commit()
    cols_legacy = [
        r[1] for r in raw.execute("PRAGMA table_info(generated_images)").fetchall()
    ]
    raw.close()
    assert "saved" not in cols_legacy, "legacy table must lack the column"

    # 2. Reopen via EncryptedKnowledgeBank — the migration adds the column.
    b2 = _make_bank(db_path=db, cipher=cipher)
    try:
        cols_after = [
            r[1]
            for r in b2._conn.execute(
                "PRAGMA table_info(generated_images)"
            ).fetchall()
        ]
        assert "saved" in cols_after, "migration must add the saved column"
        # The pre-existing row survived and reads as not-saved.
        metas = b2.list_generated_images()
        assert len(metas) == 1
        assert metas[0].image_id == iid
        assert metas[0].saved is False
        # And the row still decrypts (migration touched no encrypted column).
        got = b2.get_generated_image(iid)
        assert got is not None and got.data == _PNG
        # Idempotent: a SECOND open does not error or duplicate the column.
        b2.close()
        b3 = _make_bank(db_path=db, cipher=cipher)
        b3.close()
    finally:
        try:
            b2.close()
        except Exception:
            pass
