ACCURATE = [
    "The run did not complete successfully.",
    "The overall run did not complete successfully.",
    "The run did not complete successfully, and no acceptance tests passed.",
    "The bill-splitter component was merged, but the overall run did not complete successfully.",
    "The run 20260721-111715-bd is marked as incomplete.",
    "No acceptance tests passed.",
    "None of the tests passed.",
    "Not all tests passed.",
    "Only 2 of 9 tests passed.",
    "The build did not finish successfully.",
    # --- realistic phrasings that add ordinary detail -----------------------
    "The run did not complete successfully because the acceptance oracle failed.",
    "The run did not complete successfully; the acceptance oracle reported a failure.",
    "The run did not complete successfully after the acceptance gate failed.",
    "The run did not complete successfully on the integrated tree.",
    "The run did not complete successfully, so the work stays open.",
    "The run did not complete successfully and will need another attempt.",
    "Unfortunately the run did not complete successfully.",
    "In short, the run did not complete successfully.",
    "The coding-fleet run did not complete successfully.",
    "This run did not complete successfully.",
    "The dispatch did not complete successfully for bill-splitter.",
    "The run did not complete successfully - the oracle stayed red.",
    "The run did not complete successfully, though bill-splitter did land.",
    "Only 2 of 9 tests passed on the integrated tree.",
    "No acceptance tests passed after the wave gate failure.",
    "The acceptance tests did not pass.",
    "The acceptance tests never passed.",
    "Tests did not pass and the run is marked as incomplete.",
    "The run finished but did not complete successfully.",
    "The suite could not run successfully.",
    "The suite did not run successfully until the third attempt.",
    "The run did not complete successfully. Another dispatch is needed.",
    "The run did not complete successfully. The acceptance-tests component was parked.",
    "The run did not complete successfully. bill-splitter was merged.",
    "The run did not complete successfully, but bill-splitter was merged.",
    "The run did not complete successfully; acceptance-tests was parked.",
    "The run did not complete successfully, and the acceptance-tests task was parked.",
    "It did not complete successfully.",
    "It was not completed successfully.",
    "The pipeline did not complete successfully.",
    "The job did not finish successfully.",
    "The execution did not complete successfully.",
    "The run has not completed successfully.",
    "The run could not complete successfully.",
    "The run failed to complete successfully.",
]
