"""
SQLite Session Persistence for the UI Transport Gateway (P1.11).

Stores conversation sessions and turns in a local SQLite database at
%LOCALAPPDATA%\\BlarAI\\sessions.db. No cloud sync. No external network calls.

Schema:
    sessions: id (UUID PK), title, created_at, updated_at, is_active
    turns: id (UUID PK), session_id (FK), role, content, pgov_status, pgov_reasons, timestamp

CASCADE delete: deleting a session removes all its turns.

At-rest encryption (Sprint 14, ADR-025):
    ``turns.content`` and ``sessions.title`` (the content-bearing columns) are
    AES-256-GCM encrypted on write and decrypted on read in
    :class:`EncryptedSessionStore`.  The DEK is dual-wrapped (TPM + offline
    recovery key) and shared with the substrate store via the same
    ``BLARAI_DEK_KEYSTORE`` env var and ``TpmSealer("BlarAI-DEKSeal")`` key name
    (ADR-025 section 2.1 -- one DEK, one envelope).

    AAD binding (ADR-025 section 2.4): both ``turns.id`` and ``sessions.id`` are
    UUID strings generated by the application **before insert**
    (``str(uuid.uuid4())``), so they are stable row identities known at insert
    time.  AAD = ``make_aad_for(table, column, row_uuid)``.

    ``session_id`` stays plaintext -- it is a relational/join key, not content
    (SDV section 5.3; encrypting it would break joins for zero confidentiality
    gain).  Low-value metadata (``role``, ``pgov_status``, ``pgov_reasons``,
    timestamps, ``is_active``) stays plaintext.

    Fail-closed: if the DEK cannot be unsealed, the store refuses to open
    (``DekEnvelopeError`` propagates out of the constructor).  There is NO
    plaintext fallback, ever.
"""

from __future__ import annotations

import json
import logging
import os
import sqlite3
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

from services.ui_gateway.src.constants import (
    SESSION_DB_DIR,
    SESSION_DB_FILENAME,
    SESSION_TITLE_MAX_CHARS,
    SESSION_TITLE_PROMPT_CHARS,
)

logger = logging.getLogger(__name__)

#: ``turns.pgov_status`` marker for INFORMATIONAL assistant turns (#655) --
#: deterministic gateway/tool output echoed into the transcript (ingest
#: previews, the bare-URL nudge, ingest decisions).  These turns are NOT model
#: output and were never PGOV-validated, so none of the model-turn statuses
#: ('approved'/'denied'/'error') is honest for them.  The column has no CHECK
#: constraint, so the new value is a pure data convention.  Two load-bearing
#: consequences, both deliberate:
#:   * The prompt-history filter (transport.send_prompt) forwards only
#:     'approved' assistant turns, so informational turns (which can carry an
#:     article-sized preview) never re-enter the model's context or the 40 KB
#:     history budget.
#:   * The WinUI renders by ``pgov_status == 'denied'`` only (ChatModels.cs
#:     ``IsDenied``), so informational turns reload as normal assistant
#:     messages with no UI change.
INFORMATIONAL_TURN_STATUS: str = "informational"


def _harden_db_file_dacl(db_path: str) -> None:
    """Apply the #637 owner-only DACL to the session DB file (defense-in-depth).

    DATA_MAP §7 item 1: lock ``sessions.db`` to (current user + SYSTEM) full
    control on top of the at-rest encryption.  Owner-preserving + fail-safe
    (``shared.security.file_dacl.ensure_owner_only_dacl`` never raises and never
    blocks access).  A no-op for ``:memory:`` stores and on non-Windows hosts.
    Called after ``sqlite3.connect`` so the DB file exists on disk.
    """
    if db_path == ":memory:":
        return
    from shared.security.file_dacl import ensure_owner_only_dacl

    ensure_owner_only_dacl(db_path)


# ---------------------------------------------------------------------------
# Title derivation
# ---------------------------------------------------------------------------


def _parse_local_datetime(iso_ts: str) -> datetime:
    """Parse a stored ISO-8601 UTC timestamp into a local-time datetime.

    Stored timestamps are UTC (``datetime.now(timezone.utc).isoformat()``);
    titles show a human-facing date, so the date is rendered in local time.
    Falls back to the current local time if the string cannot be parsed, so
    a single malformed historical row never breaks the title backfill.
    """
    try:
        dt = datetime.fromisoformat(iso_ts)
    except (ValueError, TypeError):
        return datetime.now()
    if dt.tzinfo is not None:
        dt = dt.astimezone()  # UTC -> local
    return dt


def derive_session_title(prompt_text: str, when: datetime) -> str:
    """Build an auto-generated session title from the first user prompt.

    Format: ``<first N chars of prompt>… \xb7 <Mon D, YYYY>`` -- for example
    ``What's the capi… \xb7 May 22, 2026``. The prompt fragment makes the
    session distinguishable by content; the date disambiguates sessions
    that open with similar prompts. ``N`` is ``SESSION_TITLE_PROMPT_CHARS``.

    Args:
        prompt_text: The user's first prompt for the session.
        when: Datetime to stamp the title with (local time expected -- the
            caller passes the first-prompt / session-creation moment).

    Returns:
        A non-empty title string, capped at ``SESSION_TITLE_MAX_CHARS``.
    """
    collapsed = " ".join(prompt_text.split())
    fragment = collapsed[:SESSION_TITLE_PROMPT_CHARS]
    if len(collapsed) > SESSION_TITLE_PROMPT_CHARS:
        fragment += "…"  # ellipsis -- signals the prompt was truncated
    date_part = f"{when:%b} {when.day}, {when.year}"
    title = f"{fragment} \xb7 {date_part}" if fragment else f"Session \xb7 {date_part}"
    return title[:SESSION_TITLE_MAX_CHARS]


# ---------------------------------------------------------------------------
# Data Classes
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class SessionSummary:
    """Lightweight session descriptor for the session list panel."""

    id: str
    """UUID of the session."""

    title: str
    """Auto-generated title from the first prompt."""

    created_at: str
    """ISO 8601 timestamp of session creation."""

    updated_at: str
    """ISO 8601 timestamp of last activity."""

    is_active: bool
    """True if this is the currently active session."""

    turn_count: int = 0
    """Number of turns in this session."""


@dataclass(frozen=True)
class Turn:
    """Single conversation turn (user or assistant)."""

    id: str
    """UUID of the turn."""

    session_id: str
    """FK to the parent session."""

    role: str
    """'user' or 'assistant'."""

    content: str
    """Text content of the turn."""

    pgov_status: str
    """'approved', 'denied', 'error', 'N/A' (user turns), or 'informational'
    (deterministic gateway/tool output — see INFORMATIONAL_TURN_STATUS)."""

    pgov_reasons: list[str] = field(default_factory=list)
    """PGOV reason codes (empty for approved or user turns)."""

    timestamp: str = ""
    """ISO 8601 timestamp of the turn."""


# ---------------------------------------------------------------------------
# Session Store
# ---------------------------------------------------------------------------


_SCHEMA_SQL: str = """
CREATE TABLE IF NOT EXISTS sessions (
    id         TEXT PRIMARY KEY,
    title      TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    is_active  INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS turns (
    id           TEXT PRIMARY KEY,
    session_id   TEXT NOT NULL,
    role         TEXT NOT NULL CHECK(role IN ('user', 'assistant')),
    content      TEXT NOT NULL DEFAULT '',
    pgov_status  TEXT NOT NULL DEFAULT 'N/A',
    pgov_reasons TEXT NOT NULL DEFAULT '[]',
    timestamp    TEXT NOT NULL,
    FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_turns_session ON turns(session_id);
"""


class SessionStore:
    """SQLite-backed session persistence.

    Usage:
        store = SessionStore(db_path=":memory:")  # or real path
        sid = store.create_session(title="My Chat")
        store.add_turn(sid, "user", "Hello", "N/A", [])
        sessions = store.list_sessions()
    """

    def __init__(self, db_path: str = ":memory:") -> None:
        """Initialize the session store.

        Args:
            db_path: Path to SQLite database file. Use ':memory:' for tests.
                For production, use SESSION_DB_PATH from constants.py.
        """
        self._db_path: str = db_path

        # Ensure directory exists for file-based DBs
        if db_path != ":memory:":
            db_dir = os.path.dirname(db_path)
            if db_dir:
                os.makedirs(db_dir, exist_ok=True)

        self._conn: sqlite3.Connection = sqlite3.connect(
            db_path,
            check_same_thread=False,
        )
        _harden_db_file_dacl(db_path)
        self._conn.execute("PRAGMA journal_mode=WAL")
        self._conn.execute("PRAGMA foreign_keys=ON")
        # secure_delete=ON (FULL): DELETEd rows are zeroed in freed pages instead
        # of just being marked free. This store is in WAL mode, so freed pages are
        # zeroed at checkpoint (rollback-journal stores zero at COMMIT).
        self._conn.execute("PRAGMA secure_delete=ON")
        self._conn.executescript(_SCHEMA_SQL)
        self._conn.commit()
        # One-time data repair: give pre-existing empty-title sessions a
        # derived title. Idempotent -- a no-op once the DB has been repaired.
        self._backfill_empty_titles()
        logger.info("SessionStore initialized: %s", db_path)

    def close(self) -> None:
        """Close the database connection."""
        self._conn.close()
        logger.info("SessionStore closed")

    def create_session(self, title: str = "") -> str:
        """Create a new session.

        Args:
            title: Session title (auto-truncated to SESSION_TITLE_MAX_CHARS).

        Returns:
            UUID string of the new session.
        """
        session_id = str(uuid.uuid4())
        now = datetime.now(timezone.utc).isoformat()
        truncated_title = title[:SESSION_TITLE_MAX_CHARS] if title else ""

        self._conn.execute(
            "INSERT INTO sessions (id, title, created_at, updated_at, is_active) "
            "VALUES (?, ?, ?, ?, 1)",
            (session_id, truncated_title, now, now),
        )
        self._conn.commit()
        logger.info("Session created: %s (%s)", session_id, truncated_title)
        return session_id

    def list_sessions(self) -> list[SessionSummary]:
        """List all sessions ordered by most recently updated.

        Returns:
            List of SessionSummary objects.
        """
        cursor = self._conn.execute(
            "SELECT s.id, s.title, s.created_at, s.updated_at, s.is_active, "
            "  (SELECT COUNT(*) FROM turns t WHERE t.session_id = s.id) AS turn_count "
            "FROM sessions s "
            "ORDER BY s.updated_at DESC"
        )
        return [
            SessionSummary(
                id=row[0],
                title=row[1],
                created_at=row[2],
                updated_at=row[3],
                is_active=bool(row[4]),
                turn_count=row[5],
            )
            for row in cursor.fetchall()
        ]

    def get_session_turns(self, session_id: str) -> list[Turn]:
        """Retrieve all turns for a session, ordered chronologically.

        Args:
            session_id: UUID of the session.

        Returns:
            List of Turn objects.
        """
        cursor = self._conn.execute(
            "SELECT id, session_id, role, content, pgov_status, pgov_reasons, timestamp "
            "FROM turns "
            "WHERE session_id = ? "
            "ORDER BY timestamp ASC",
            (session_id,),
        )
        return [
            Turn(
                id=row[0],
                session_id=row[1],
                role=row[2],
                content=row[3],
                pgov_status=row[4],
                pgov_reasons=json.loads(row[5]) if row[5] else [],
                timestamp=row[6],
            )
            for row in cursor.fetchall()
        ]

    def get_turns(self, session_id: str) -> list[Turn]:
        """Alias for get_session_turns()."""
        return self.get_session_turns(session_id)

    def add_turn(
        self,
        session_id: str,
        role: str,
        content: str,
        pgov_status: str,
        pgov_reasons: list[str],
    ) -> str:
        """Add a turn to a session.

        Args:
            session_id: UUID of the parent session.
            role: 'user' or 'assistant'.
            content: Text content.
            pgov_status: 'approved', 'denied', 'error', or 'N/A'.
            pgov_reasons: List of PGOV reason code strings.

        Returns:
            UUID of the new turn.

        Raises:
            ValueError: If role is not 'user' or 'assistant'.
        """
        if role not in ("user", "assistant"):
            raise ValueError(f"Invalid role: {role!r}. Must be 'user' or 'assistant'.")

        turn_id = str(uuid.uuid4())
        now = datetime.now(timezone.utc).isoformat()

        self._conn.execute(
            "INSERT INTO turns (id, session_id, role, content, pgov_status, pgov_reasons, timestamp) "
            "VALUES (?, ?, ?, ?, ?, ?, ?)",
            (turn_id, session_id, role, content, pgov_status, json.dumps(pgov_reasons), now),
        )
        # Update session's updated_at
        self._conn.execute(
            "UPDATE sessions SET updated_at = ? WHERE id = ?",
            (now, session_id),
        )
        self._conn.commit()
        return turn_id

    def delete_session(self, session_id: str) -> bool:
        """Delete a session and all its turns (CASCADE).

        Args:
            session_id: UUID of the session to delete.

        Returns:
            True if the session existed and was deleted.
        """
        cursor = self._conn.execute(
            "DELETE FROM sessions WHERE id = ?",
            (session_id,),
        )
        self._conn.commit()
        deleted = cursor.rowcount > 0
        if deleted:
            logger.info("Session deleted: %s (CASCADE turns)", session_id)
        return deleted

    def clear_session_turns(self, session_id: str) -> int:
        """Delete all turns for a session, preserving the session record.

        Args:
            session_id: UUID of the session.

        Returns:
            Number of turns deleted.
        """
        cursor = self._conn.execute(
            "DELETE FROM turns WHERE session_id = ?",
            (session_id,),
        )
        self._conn.commit()
        logger.info("Cleared %d turns for session %s", cursor.rowcount, session_id)
        return cursor.rowcount

    def set_active_session(self, session_id: str) -> None:
        """Mark a session as active and deactivate all others.

        Args:
            session_id: UUID of the session to activate.
        """
        self._conn.execute("UPDATE sessions SET is_active = 0")
        self._conn.execute(
            "UPDATE sessions SET is_active = 1 WHERE id = ?",
            (session_id,),
        )
        self._conn.commit()

    # -- Title management --------------------------------------------------

    def set_title_if_empty(self, session_id: str, title: str) -> bool:
        """Set a session's title only if it is currently empty.

        Applies the auto-generated title on a session's first user prompt.
        The ``WHERE title = ''`` guard makes this idempotent and ensures it
        can never clobber a title the user set explicitly via /rename.

        Args:
            session_id: UUID of the session.
            title: Title to set (truncated to ``SESSION_TITLE_MAX_CHARS``).

        Returns:
            True if a row was updated (title was empty and is now set).
        """
        truncated = title[:SESSION_TITLE_MAX_CHARS]
        cursor = self._conn.execute(
            "UPDATE sessions SET title = ? WHERE id = ? AND title = ''",
            (truncated, session_id),
        )
        self._conn.commit()
        updated = cursor.rowcount > 0
        if updated:
            logger.info("Session title set: %s (%s)", session_id, truncated)
        return updated

    def update_session_title(self, session_id: str, title: str) -> bool:
        """Set a session's title unconditionally -- backs the /rename command.

        Unlike :meth:`set_title_if_empty`, this overwrites any existing
        title; that is the intent of an explicit user rename.

        Args:
            session_id: UUID of the session.
            title: New title (truncated to ``SESSION_TITLE_MAX_CHARS``).

        Returns:
            True if the session existed and was updated.
        """
        truncated = title[:SESSION_TITLE_MAX_CHARS]
        cursor = self._conn.execute(
            "UPDATE sessions SET title = ? WHERE id = ?",
            (truncated, session_id),
        )
        self._conn.commit()
        updated = cursor.rowcount > 0
        if updated:
            logger.info("Session renamed: %s (%s)", session_id, truncated)
        return updated

    def _backfill_empty_titles(self) -> int:
        """One-time data repair: give empty-title sessions a derived title.

        Historically the auto-title feature was unimplemented, so every
        session row was stored with an empty title and surfaced in the UI
        as the indistinguishable placeholder "New session". This pass
        repairs that bad data: for each session whose title is still empty,
        it derives a title from the session's first user turn (the same
        rule new sessions now follow) and writes it back.

        Purely additive and idempotent:
          - Only sessions with an empty title are touched; existing titles
            (including /rename titles) are never modified.
          - A session with no user turn is left empty -- genuinely unused,
            with no content to name it after.
          - After one run, repaired sessions no longer match the
            empty-title filter, so subsequent runs are no-ops.

        Returns:
            Number of sessions backfilled.
        """
        rows = self._conn.execute(
            "SELECT id, created_at FROM sessions WHERE title = ''"
        ).fetchall()
        backfilled = 0
        for session_id, created_at in rows:
            turn = self._conn.execute(
                "SELECT content, timestamp FROM turns "
                "WHERE session_id = ? AND role = 'user' "
                "ORDER BY timestamp ASC LIMIT 1",
                (session_id,),
            ).fetchone()
            if turn is None:
                continue  # no user turn -- nothing to name the session after
            content, turn_ts = turn
            when = _parse_local_datetime(created_at or turn_ts)
            title = derive_session_title(content, when)
            self._conn.execute(
                "UPDATE sessions SET title = ? WHERE id = ?",
                (title, session_id),
            )
            backfilled += 1
        if backfilled:
            self._conn.commit()
            logger.info("Backfilled %d empty session title(s)", backfilled)
        return backfilled


# ============================================================================
# Encrypted variant (Sprint 14, ADR-025)
# ============================================================================


# Version marker stored in ``sessions_meta`` to identify encrypted stores.
_SESSIONS_ENCRYPTION_VERSION: str = "1"

# SQL for the sessions_meta table -- a simple key/value store for schema metadata.
_META_TABLE_SQL: str = """
CREATE TABLE IF NOT EXISTS sessions_meta (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
"""


def _is_encrypted_blob(value: Any) -> bool:
    """Return True if *value* looks like an AES-GCM ciphertext blob.

    An encrypted field is stored as a ``BLOB`` whose first byte is the
    ``FIELD_CIPHER_VERSION`` constant (0x01).  Plaintext fields are ``TEXT``
    (Python ``str``).  This check lets the migration and backfill paths detect
    already-encrypted rows without a dedicated schema column.
    """
    from shared.security.field_cipher import FIELD_CIPHER_VERSION
    return (
        isinstance(value, (bytes, bytearray))
        and len(value) > 0
        and value[0] == FIELD_CIPHER_VERSION
    )


class EncryptedSessionStore:
    """AES-GCM-encrypted variant of SessionStore (Sprint 14, ADR-025).

    Sensitive columns encrypted on write / decrypted on read:
    - ``turns.content`` -- every conversation turn's text.
    - ``sessions.title`` -- the prompt-derived session title.

    ``session_id`` and all other metadata (``role``, ``pgov_status``,
    ``pgov_reasons``, timestamps, ``is_active``) stay plaintext -- they are
    relational/metadata fields, not content (ADR-025 section 3, SDV section 5.3).

    AAD binding (ADR-025 section 2.4): both ``turns.id`` and ``sessions.id``
    are UUID strings generated by the application **before insert** -- stable
    row identities known at insert time.
    AAD = ``make_aad_for(table, column, row_uuid)``.

    Fail-closed: the constructor raises ``DekEnvelopeError`` if the DEK cannot
    be unsealed.  There is NO plaintext fallback.

    ``has_encryption: bool = True`` -- production-wiring regression lock.

    Args:
        db_path: Path to the sessions SQLite file (``:memory:`` for tests).
        cipher:  :class:`~shared.security.field_cipher.FieldCipher` instance,
                 constructed by the caller after unsealing the DEK envelope.
    """

    #: Regression-lock attribute: any code that constructs the store can assert
    #: ``store.has_encryption is True`` to detect a future silent-wiring failure.
    has_encryption: bool = True

    def __init__(
        self,
        db_path: str,
        cipher: "FieldCipher",  # type: ignore[name-defined]  # noqa: F821
    ) -> None:
        from shared.security.field_cipher import FieldCipher  # local import; no circular dep
        if not isinstance(cipher, FieldCipher):
            raise TypeError(
                "EncryptedSessionStore requires a FieldCipher instance; "
                f"got {type(cipher).__name__!r}.  Pass a FieldCipher derived "
                "from the unsealed DEK."
            )
        self._db_path: str = db_path
        self._cipher = cipher

        # Ensure directory exists for file-based DBs
        if db_path != ":memory:":
            db_dir = os.path.dirname(db_path)
            if db_dir:
                os.makedirs(db_dir, exist_ok=True)

        self._conn: sqlite3.Connection = sqlite3.connect(
            db_path,
            check_same_thread=False,
        )
        _harden_db_file_dacl(db_path)
        self._conn.execute("PRAGMA journal_mode=WAL")
        self._conn.execute("PRAGMA foreign_keys=ON")
        # secure_delete=ON (FULL): DELETEd rows are zeroed in freed pages instead
        # of just being marked free. This store is in WAL mode, so freed pages are
        # zeroed at checkpoint (rollback-journal stores zero at COMMIT).
        self._conn.execute("PRAGMA secure_delete=ON")
        self._conn.executescript(_SCHEMA_SQL)
        self._conn.executescript(_META_TABLE_SQL)
        # Mark this store as encryption-version 1.
        self._conn.execute(
            "INSERT OR IGNORE INTO sessions_meta(key, value) VALUES('encryption_version', ?)",
            (_SESSIONS_ENCRYPTION_VERSION,),
        )
        self._conn.commit()
        # Backfill: sessions with empty titles get derived titles (via decrypted
        # content).  Idempotent -- a no-op once previously-empty titles have been
        # set.
        self._backfill_empty_titles()
        logger.info("EncryptedSessionStore initialized: %s", db_path)

    def close(self) -> None:
        """Close the database connection."""
        self._conn.close()
        logger.info("EncryptedSessionStore closed")

    @property
    def field_cipher(self) -> "FieldCipher":  # type: ignore[name-defined]  # noqa: F821
        """The store's :class:`FieldCipher` (the shared-DEK envelope cipher).

        Exposed read-only so sibling shared-DEK consumers in the SAME process
        -- specifically the #655 ingest-staging writer in the gateway
        (``shared/security/ingest_staging.write_staged``) -- can encrypt under
        the one-DEK envelope (ADR-025 section 2.1) without duplicating the
        sealer/keystore resolution policy in :func:`build_session_store`.

        This adds no at-rest or cross-process surface: the derived subkeys
        already live in this process's memory; the property only spares a
        second envelope-unseal of the same DEK.
        """
        return self._cipher

    # -- Encryption helpers ------------------------------------------------

    def _enc_turn_content(self, turn_id: str, plaintext: str) -> bytes:
        """Encrypt ``turns.content`` for *turn_id*."""
        from shared.security.field_cipher import make_aad_for
        return self._cipher.encrypt(
            plaintext.encode("utf-8"),
            aad=make_aad_for("turns", "content", turn_id),
        )

    def _dec_turn_content(self, turn_id: str, blob: Any) -> str:
        """Decrypt ``turns.content`` for *turn_id*.  Fail-closed."""
        from shared.security.field_cipher import FieldCipherError, make_aad_for
        if not _is_encrypted_blob(blob):
            # Plaintext row -- pre-migration or in-memory store without migration.
            return blob if isinstance(blob, str) else bytes(blob).decode("utf-8")
        try:
            return self._cipher.decrypt(
                bytes(blob),
                aad=make_aad_for("turns", "content", turn_id),
            ).decode("utf-8")
        except FieldCipherError as exc:
            raise RuntimeError(
                f"EncryptedSessionStore: failed to decrypt turns.content for "
                f"turn_id={turn_id!r} -- refusing to return plaintext"
            ) from exc

    def _enc_session_title(self, session_id: str, plaintext: str) -> bytes:
        """Encrypt ``sessions.title`` for *session_id*."""
        from shared.security.field_cipher import make_aad_for
        return self._cipher.encrypt(
            plaintext.encode("utf-8"),
            aad=make_aad_for("sessions", "title", session_id),
        )

    def _dec_session_title(self, session_id: str, blob: Any) -> str:
        """Decrypt ``sessions.title`` for *session_id*.  Fail-closed.

        Empty title (stored as b'' or '') is returned as '' without decryption --
        an empty title is valid state (newly-created session before backfill).
        """
        from shared.security.field_cipher import FieldCipherError, make_aad_for
        if blob is None or blob == b"" or blob == "":
            return ""
        if not _is_encrypted_blob(blob):
            # Plaintext row -- pre-migration or in-memory store without migration.
            return blob if isinstance(blob, str) else bytes(blob).decode("utf-8")
        try:
            return self._cipher.decrypt(
                bytes(blob),
                aad=make_aad_for("sessions", "title", session_id),
            ).decode("utf-8")
        except FieldCipherError as exc:
            raise RuntimeError(
                f"EncryptedSessionStore: failed to decrypt sessions.title for "
                f"session_id={session_id!r} -- refusing to return plaintext"
            ) from exc

    # -- Session CRUD -------------------------------------------------------

    def create_session(self, title: str = "") -> str:
        """Create a new session with the title AES-GCM encrypted.

        Args:
            title: Session title (truncated to ``SESSION_TITLE_MAX_CHARS``).

        Returns:
            UUID string of the new session.
        """
        session_id = str(uuid.uuid4())
        now = datetime.now(timezone.utc).isoformat()
        truncated_title = title[:SESSION_TITLE_MAX_CHARS] if title else ""

        # Encrypt the title; empty title is stored as '' (not as a cipher blob).
        if truncated_title:
            enc_title: Any = self._enc_session_title(session_id, truncated_title)
        else:
            enc_title = ""

        self._conn.execute(
            "INSERT INTO sessions (id, title, created_at, updated_at, is_active) "
            "VALUES (?, ?, ?, ?, 1)",
            (session_id, enc_title, now, now),
        )
        self._conn.commit()
        logger.info("EncryptedSessionStore: session created: %s", session_id)
        return session_id

    def list_sessions(self) -> list[SessionSummary]:
        """List all sessions ordered by most recently updated.

        Decrypts ``sessions.title`` for each row on read.

        Bulk-read quarantine policy (ADR-025 §2.7 amendment, 2026-06-06):
        A single legacy or tampered row must not deny access to the entire
        store -- that would be a self-inflicted availability DoS, and
        availability is a security property (CIA triad).  When a row cannot
        be decrypted (e.g. encrypted under a prior dev-mode key after a
        dev->production key transition) it is QUARANTINED: omitted from the
        result set and logged at WARNING level with a stable event code
        SESSION_ROW_DECRYPT_QUARANTINE.  Confidentiality and integrity are
        fully preserved -- plaintext is never returned, tampered data is
        never trusted -- and the quarantine event makes a bad row MORE
        visible than a generic store-wide crash.

        SINGLE-RECORD callers (set_title_if_empty, update_session_title)
        retain the hard fail-closed posture: the caller named that one
        session explicitly, so a decrypt failure is the right loud signal.

        Returns:
            List of SessionSummary objects with plaintext titles.
            Rows that cannot be decrypted are omitted (quarantined).
        """
        cursor = self._conn.execute(
            "SELECT s.id, s.title, s.created_at, s.updated_at, s.is_active, "
            "  (SELECT COUNT(*) FROM turns t WHERE t.session_id = s.id) AS turn_count "
            "FROM sessions s "
            "ORDER BY s.updated_at DESC"
        )
        summaries: list[SessionSummary] = []
        quarantined: int = 0
        for row in cursor.fetchall():
            session_id, raw_title, created_at, updated_at, is_active, turn_count = row
            try:
                title = self._dec_session_title(session_id, raw_title)
            except RuntimeError as exc:
                quarantined += 1
                logger.warning(
                    "SESSION_ROW_DECRYPT_QUARANTINE event=SESSION_ROW_DECRYPT_QUARANTINE "
                    "session_id=%r reason=%r -- row excluded from list_sessions result",
                    session_id,
                    str(exc),
                )
                continue
            summaries.append(SessionSummary(
                id=session_id,
                title=title,
                created_at=created_at,
                updated_at=updated_at,
                is_active=bool(is_active),
                turn_count=turn_count,
            ))
        if quarantined:
            logger.warning(
                "SESSION_ROW_DECRYPT_QUARANTINE summary: %d session row(s) quarantined "
                "in list_sessions -- check key rotation / dev->prod key transition",
                quarantined,
            )
        return summaries

    def get_session_turns(self, session_id: str) -> list[Turn]:
        """Retrieve all turns for a session, decrypting ``content`` on read.

        Bulk-read quarantine policy (ADR-025 §2.7 amendment, 2026-06-06):
        Same rationale as list_sessions -- a single un-decryptable turn
        (legacy key, tampered ciphertext) must not deny access to all other
        turns in the session.  Un-decryptable turns are quarantined: omitted
        from the result and logged with SESSION_ROW_DECRYPT_QUARANTINE.
        Plaintext is never returned from a bad row.

        Args:
            session_id: UUID of the session.

        Returns:
            List of Turn objects with plaintext content.
            Turns that cannot be decrypted are omitted (quarantined).
        """
        cursor = self._conn.execute(
            "SELECT id, session_id, role, content, pgov_status, pgov_reasons, timestamp "
            "FROM turns "
            "WHERE session_id = ? "
            "ORDER BY timestamp ASC",
            (session_id,),
        )
        turns: list[Turn] = []
        quarantined: int = 0
        for row in cursor.fetchall():
            turn_id, sess_id, role, raw_content, pgov_status, pgov_reasons_raw, ts = row
            try:
                content = self._dec_turn_content(turn_id, raw_content)
            except RuntimeError as exc:
                quarantined += 1
                logger.warning(
                    "SESSION_ROW_DECRYPT_QUARANTINE event=SESSION_ROW_DECRYPT_QUARANTINE "
                    "turn_id=%r session_id=%r reason=%r -- turn excluded from "
                    "get_session_turns result",
                    turn_id,
                    session_id,
                    str(exc),
                )
                continue
            turns.append(Turn(
                id=turn_id,
                session_id=sess_id,
                role=role,
                content=content,
                pgov_status=pgov_status,
                pgov_reasons=json.loads(pgov_reasons_raw) if pgov_reasons_raw else [],
                timestamp=ts,
            ))
        if quarantined:
            logger.warning(
                "SESSION_ROW_DECRYPT_QUARANTINE summary: %d turn row(s) quarantined "
                "in get_session_turns(session_id=%r) -- check key rotation / "
                "dev->prod key transition",
                quarantined,
                session_id,
            )
        return turns

    def get_turns(self, session_id: str) -> list[Turn]:
        """Alias for get_session_turns()."""
        return self.get_session_turns(session_id)

    def add_turn(
        self,
        session_id: str,
        role: str,
        content: str,
        pgov_status: str,
        pgov_reasons: list[str],
    ) -> str:
        """Encrypt ``content`` and add a turn to a session.

        Args:
            session_id: UUID of the parent session.
            role: 'user' or 'assistant'.
            content: Plaintext text content (encrypted before storage).
            pgov_status: 'approved', 'denied', 'error', or 'N/A'.
            pgov_reasons: List of PGOV reason code strings.

        Returns:
            UUID of the new turn.

        Raises:
            ValueError: If role is not 'user' or 'assistant'.
        """
        if role not in ("user", "assistant"):
            raise ValueError(f"Invalid role: {role!r}. Must be 'user' or 'assistant'.")

        turn_id = str(uuid.uuid4())
        now = datetime.now(timezone.utc).isoformat()

        enc_content = self._enc_turn_content(turn_id, content)

        self._conn.execute(
            "INSERT INTO turns (id, session_id, role, content, pgov_status, pgov_reasons, timestamp) "
            "VALUES (?, ?, ?, ?, ?, ?, ?)",
            (turn_id, session_id, role, enc_content, pgov_status, json.dumps(pgov_reasons), now),
        )
        # Update session's updated_at
        self._conn.execute(
            "UPDATE sessions SET updated_at = ? WHERE id = ?",
            (now, session_id),
        )
        self._conn.commit()
        return turn_id

    def delete_session(self, session_id: str) -> bool:
        """Delete a session and all its turns (CASCADE).

        Args:
            session_id: UUID of the session to delete.

        Returns:
            True if the session existed and was deleted.
        """
        cursor = self._conn.execute(
            "DELETE FROM sessions WHERE id = ?",
            (session_id,),
        )
        self._conn.commit()
        deleted = cursor.rowcount > 0
        if deleted:
            logger.info(
                "EncryptedSessionStore: session deleted: %s (CASCADE turns)", session_id
            )
        return deleted

    def clear_session_turns(self, session_id: str) -> int:
        """Delete all turns for a session, preserving the session record.

        Args:
            session_id: UUID of the session.

        Returns:
            Number of turns deleted.
        """
        cursor = self._conn.execute(
            "DELETE FROM turns WHERE session_id = ?",
            (session_id,),
        )
        self._conn.commit()
        logger.info(
            "EncryptedSessionStore: cleared %d turns for session %s",
            cursor.rowcount, session_id,
        )
        return cursor.rowcount

    def set_active_session(self, session_id: str) -> None:
        """Mark a session as active and deactivate all others."""
        self._conn.execute("UPDATE sessions SET is_active = 0")
        self._conn.execute(
            "UPDATE sessions SET is_active = 1 WHERE id = ?",
            (session_id,),
        )
        self._conn.commit()

    # -- Title management --------------------------------------------------

    def set_title_if_empty(self, session_id: str, title: str) -> bool:
        """Set a session's title (encrypted) only if it is currently empty.

        In the encrypted store, "empty" means the raw title decrypts to '' (or
        is stored as '' directly).  The check is performed by reading the current
        raw title and decrypting it; if it decrypts to '' the new title is
        encrypted and written back.

        Args:
            session_id: UUID of the session.
            title: Title to set (truncated to ``SESSION_TITLE_MAX_CHARS``).

        Returns:
            True if a row was updated (title was empty and is now set).
        """
        row = self._conn.execute(
            "SELECT title FROM sessions WHERE id = ?", (session_id,)
        ).fetchone()
        if row is None:
            return False  # unknown session

        current_title = self._dec_session_title(session_id, row[0])
        if current_title != "":
            return False  # title already set -- do not clobber

        truncated = title[:SESSION_TITLE_MAX_CHARS]
        enc_title = self._enc_session_title(session_id, truncated)
        self._conn.execute(
            "UPDATE sessions SET title = ? WHERE id = ?",
            (enc_title, session_id),
        )
        self._conn.commit()
        logger.info("EncryptedSessionStore: session title set: %s", session_id)
        return True

    def update_session_title(self, session_id: str, title: str) -> bool:
        """Set a session's title unconditionally -- backs the /rename command.

        Args:
            session_id: UUID of the session.
            title: New title (truncated to ``SESSION_TITLE_MAX_CHARS``).

        Returns:
            True if the session existed and was updated.
        """
        row = self._conn.execute(
            "SELECT id FROM sessions WHERE id = ?", (session_id,)
        ).fetchone()
        if row is None:
            return False

        truncated = title[:SESSION_TITLE_MAX_CHARS]
        enc_title = self._enc_session_title(session_id, truncated)
        self._conn.execute(
            "UPDATE sessions SET title = ? WHERE id = ?",
            (enc_title, session_id),
        )
        self._conn.commit()
        logger.info("EncryptedSessionStore: session renamed: %s", session_id)
        return True

    def _backfill_empty_titles(self) -> int:
        """One-time data repair: give empty-title sessions a derived title.

        For the encrypted store, "empty" means the raw title value is '' (empty
        string) -- empty titles are never encrypted.  After backfill the derived
        title is written back encrypted.

        The first user turn's ``content`` may already be an encrypted blob if the
        store was previously opened with encryption; it is decrypted before
        deriving the title.

        Returns:
            Number of sessions backfilled.
        """
        # Only fetch sessions whose raw title column is the empty string ''.
        # Encrypted titles are stored as bytes (BLOB), not ''.  Using SQL
        # filtering here avoids calling _dec_session_title on encrypted blobs
        # for sessions that already have a title -- which matters when the store
        # is opened with a different key (e.g. during testing or key rotation).
        rows = self._conn.execute(
            "SELECT id, created_at FROM sessions WHERE title = ''"
        ).fetchall()
        backfilled = 0
        quarantined = 0
        for session_id, created_at in rows:
            turn = self._conn.execute(
                "SELECT id, content, timestamp FROM turns "
                "WHERE session_id = ? AND role = 'user' "
                "ORDER BY timestamp ASC LIMIT 1",
                (session_id,),
            ).fetchone()
            if turn is None:
                continue  # no user turn -- nothing to name the session after

            turn_id, raw_content, turn_ts = turn

            # Bulk-read quarantine policy (ADR-025 §2.7 amendment, 2026-06-06):
            # A single un-decryptable turn (legacy key, tampered ciphertext)
            # must not abort construction of the store and deny access to all
            # other sessions.  Quarantine the row: skip it, emit the stable
            # event code, and continue.  Plaintext is never returned.
            try:
                content = self._dec_turn_content(turn_id, raw_content)
            except RuntimeError as exc:
                quarantined += 1
                logger.warning(
                    "SESSION_ROW_DECRYPT_QUARANTINE event=SESSION_ROW_DECRYPT_QUARANTINE "
                    "turn_id=%r session_id=%r reason=%r -- turn excluded from "
                    "_backfill_empty_titles; session title will remain empty",
                    turn_id,
                    session_id,
                    str(exc),
                )
                continue

            when = _parse_local_datetime(created_at or turn_ts)
            title = derive_session_title(content, when)

            # Encrypt and write the derived title back.
            enc_title = self._enc_session_title(session_id, title)
            self._conn.execute(
                "UPDATE sessions SET title = ? WHERE id = ?",
                (enc_title, session_id),
            )
            backfilled += 1

        if quarantined:
            logger.warning(
                "SESSION_ROW_DECRYPT_QUARANTINE summary: %d session(s) quarantined "
                "during _backfill_empty_titles -- those sessions retain an empty title; "
                "check key rotation / dev->prod key transition",
                quarantined,
            )
        if backfilled:
            self._conn.commit()
            logger.info(
                "EncryptedSessionStore: backfilled %d empty session title(s)", backfilled
            )
        return backfilled


# ============================================================================
# Migration utility (ADR-025 section 3)
# ============================================================================


def migrate_plaintext_to_encrypted(
    db_path: str,
    cipher: "FieldCipher",  # type: ignore[name-defined]  # noqa: F821
    *,
    dry_run: bool = False,
) -> dict[str, int]:
    """Encrypt plaintext rows in an existing sessions.db in place.

    Algorithm:
    1. Open the DB.
    2. For each turn row where ``content`` is a plaintext string:
       a. Encrypt ``content`` with AAD bound to the turn UUID.
       b. Write back the ciphertext blob.
    3. For each session row where ``title`` is a non-empty plaintext string:
       a. Encrypt ``title`` with AAD bound to the session UUID.
       b. Write back the ciphertext blob.
    4. Skip rows that are already encrypted (version-byte check -- idempotent).
    5. VACUUM to scrub freed pages containing old plaintext.

    Returns a dict with counts:
    ``{"turns_migrated": N, "titles_migrated": M,
       "turns_already_encrypted": A, "titles_already_encrypted": B,
       "errors": K}``.

    Args:
        db_path:  Path to the SQLite file.
        cipher:   :class:`~shared.security.field_cipher.FieldCipher` instance.
        dry_run:  If True, do not write anything; just report what would be done.
    """
    from shared.security.field_cipher import make_aad_for

    conn = sqlite3.connect(db_path, check_same_thread=False)
    try:
        # Ensure the sessions_meta table exists and mark encryption version --
        # skip if dry_run (no writes at all).
        if not dry_run:
            conn.executescript(_META_TABLE_SQL)
            conn.execute(
                "INSERT OR IGNORE INTO sessions_meta(key, value) VALUES('encryption_version', ?)",
                (_SESSIONS_ENCRYPTION_VERSION,),
            )
            conn.commit()

        turns_migrated = 0
        turns_already = 0
        titles_migrated = 0
        titles_already = 0
        errors = 0

        # -- Migrate turns.content -----------------------------------------
        turn_rows = conn.execute(
            "SELECT id, content FROM turns"
        ).fetchall()

        for turn_id, raw_content in turn_rows:
            if _is_encrypted_blob(raw_content):
                turns_already += 1
                continue
            try:
                plaintext = (
                    raw_content
                    if isinstance(raw_content, str)
                    else bytes(raw_content).decode("utf-8")
                )
                enc_content = cipher.encrypt(
                    plaintext.encode("utf-8"),
                    aad=make_aad_for("turns", "content", turn_id),
                )
                if not dry_run:
                    conn.execute(
                        "UPDATE turns SET content = ? WHERE id = ?",
                        (enc_content, turn_id),
                    )
                turns_migrated += 1
            except Exception as exc:  # noqa: BLE001
                logger.error("Migration error on turn %s: %s", turn_id, exc)
                errors += 1

        # -- Migrate sessions.title ----------------------------------------
        session_rows = conn.execute(
            "SELECT id, title FROM sessions"
        ).fetchall()

        for session_id, raw_title in session_rows:
            # Empty titles stay as '' -- never encrypt an empty title.
            if raw_title is None or raw_title == "" or raw_title == b"":
                continue
            if _is_encrypted_blob(raw_title):
                titles_already += 1
                continue
            try:
                plaintext = (
                    raw_title
                    if isinstance(raw_title, str)
                    else bytes(raw_title).decode("utf-8")
                )
                enc_title = cipher.encrypt(
                    plaintext.encode("utf-8"),
                    aad=make_aad_for("sessions", "title", session_id),
                )
                if not dry_run:
                    conn.execute(
                        "UPDATE sessions SET title = ? WHERE id = ?",
                        (enc_title, session_id),
                    )
                titles_migrated += 1
            except Exception as exc:  # noqa: BLE001
                logger.error("Migration error on session %s title: %s", session_id, exc)
                errors += 1

        if not dry_run:
            conn.commit()
            # VACUUM to scrub freed pages that still contain old plaintext.
            conn.execute("VACUUM")

        return {
            "turns_migrated": turns_migrated,
            "titles_migrated": titles_migrated,
            "turns_already_encrypted": turns_already,
            "titles_already_encrypted": titles_already,
            "errors": errors,
        }
    finally:
        conn.close()


def verify_no_plaintext(
    db_path: str,
    plaintext_samples: list[bytes],
) -> list[str]:
    """Whole-file scan asserting no plaintext sample appears in raw DB bytes.

    Reads the raw file bytes (post-VACUUM) and searches for each supplied
    sample. Returns a list of violation strings (empty = all clear).

    Args:
        db_path:           Path to the SQLite file.
        plaintext_samples: List of plaintext byte strings to search for.
    """
    from pathlib import Path

    raw = Path(db_path).read_bytes()
    violations: list[str] = []
    for sample in plaintext_samples:
        if len(sample) < 4:
            continue  # too short to be meaningful
        if sample in raw:
            violations.append(
                f"Plaintext sample found in raw DB file: {sample[:40]!r}..."
            )
    return violations


# ============================================================================
# Fail-Closed factory -- the ONLY production construction path
# ============================================================================


class StoreProvisioningError(RuntimeError):
    """Raised by the store factories when a required keystore is absent in
    production mode (``dev_mode=False``).

    This is the symmetric counterpart to ``AuditProvisioningError`` in the
    Policy Agent (ADR-025 §2.8(a)).  A production boot with
    ``BLARAI_DEK_KEYSTORE`` unset is a misconfiguration -- the store refuses
    to start rather than silently falling back to the public ``SoftwareSealer``
    key (which is not a security boundary).  Fail-closed: no plaintext
    fallback, no SoftwareSealer in production.
    """


def build_session_store(
    db_path: str,
    *,
    dev_mode: bool = False,
) -> "EncryptedSessionStore":
    """Build an :class:`EncryptedSessionStore` -- the production factory.

    Follows the same DEK-envelope construction pattern as ``_build_substrate``
    in the Orchestrator entrypoint (EA-3 reference pattern, ADR-025):

    - Dev/test path (``dev_mode=True`` **explicit**, or ``db_path == ':memory:'``):
      ``SoftwareSealer`` + ephemeral keystore alongside the DB.  The dev path
      is an EXPLICIT, LOUD opt-in -- it is NOT the silent default for a missing
      env var.
    - Production path (``dev_mode=False``, ``BLARAI_DEK_KEYSTORE`` set):
      ``TpmSealer("BlarAI-DEKSeal")`` + the persisted keystore.
    - Misconfiguration (``dev_mode=False``, ``BLARAI_DEK_KEYSTORE`` MISSING,
      non-``:memory:`` db_path): REFUSE TO START -- raises
      :class:`StoreProvisioningError`.  Symmetric with the audit
      refuse-to-start (ADR-025 §2.8(a)).

    The session store and the substrate store share the **same DEK** (same
    ``BLARAI_DEK_KEYSTORE`` keystore path, same ``TpmSealer`` key name
    ``"BlarAI-DEKSeal"``).  If both stores are constructed in the same process
    they load the same keystore file, and the ``TpmSealer`` unseals the same DEK
    -- one DEK, two consumers (ADR-025 section 2.1).  The envelope is loaded (not
    re-created) if the keystore already exists, so re-opening an existing DB
    reuses the persisted DEK.

    Args:
        db_path:  Path to the sessions SQLite file.
        dev_mode: Caller-supplied dev-mode flag (from launcher / entrypoint).
                  ``True`` permits the ``SoftwareSealer`` path and is intended
                  only for development and test.  Defaults to ``False``
                  (production posture -- refuse if keystore is absent).

    Returns:
        A fully-initialized :class:`EncryptedSessionStore`.

    Raises:
        StoreProvisioningError: if ``dev_mode=False`` and
            ``BLARAI_DEK_KEYSTORE`` is not set (and ``db_path != ':memory:'``).
            Production refuses to construct with a SoftwareSealer.
        DekEnvelopeError:   if the DEK cannot be unsealed (fail-closed).
        DevModeSealerError: if a SoftwareSealer is used without dev_mode=True.
    """
    from pathlib import Path

    from shared.security.dek_envelope import (
        DekEnvelope,
        build_envelope,
        generate_recovery_key,
    )
    from shared.security.field_cipher import FieldCipher, derive_subkeys
    from shared.security.tpm_sealer import SoftwareSealer

    keystore_env = os.environ.get("BLARAI_DEK_KEYSTORE", "")

    if db_path == ":memory:":
        # Pure in-memory -- always dev/test; envelope is ephemeral, not saved.
        sealer = SoftwareSealer()
        recovery_key = generate_recovery_key()
        envelope = DekEnvelope.create(sealer=sealer, recovery_key=recovery_key)
    elif dev_mode:
        # Explicit dev/test path -- SoftwareSealer with ephemeral keystore
        # alongside the DB.  LOUD warning so this is never silent.
        sealer = SoftwareSealer()
        recovery_key = generate_recovery_key()
        keystore_path = Path(db_path).with_suffix(".keystore.json")
        if keystore_path.exists():
            envelope = DekEnvelope.load(sealer=sealer, keystore_path=keystore_path)
        else:
            envelope = build_envelope(
                sealer=sealer,
                recovery_key=recovery_key,
                keystore_path=keystore_path,
                dev_mode=True,
            )
            logger.warning(
                "SessionStore: created ephemeral DEK keystore at %s "
                "(dev mode -- SoftwareSealer, no TPM). "
                "Run the ceremony to provision a real TPM-sealed DEK.",
                keystore_path,
            )
    elif not keystore_env:
        # Production path with missing keystore -- REFUSE TO START.
        # Symmetric with the audit refuse-to-start (ADR-025 §2.8(a)).
        # A missing BLARAI_DEK_KEYSTORE in production is a misconfiguration;
        # silently falling back to SoftwareSealer would encrypt under a
        # hard-coded public key, providing NO security guarantee.
        logger.error(
            "BLARAI_DEK_KEYSTORE is not set and dev_mode=False -- refusing to "
            "start.  Production requires a TPM-sealed DEK keystore.  Run the "
            "provisioning ceremony or set dev_mode=True for development use "
            "(ADR-025 §2.8(a))."
        )
        raise StoreProvisioningError(
            "BLARAI_DEK_KEYSTORE is not set in production mode (dev_mode=False).  "
            "Production requires a TPM-sealed DEK keystore; constructing a session "
            "store with the SoftwareSealer is NOT permitted outside an explicit "
            "dev_mode=True context.  Run the provisioning ceremony or start the "
            "launcher in development mode (ADR-025 §2.8(a))."
        )
    else:
        # Production path -- TpmSealer.
        from shared.security.tpm_sealer import TpmSealer
        sealer = TpmSealer(key_name="BlarAI-DEKSeal")
        envelope = DekEnvelope.load(sealer=sealer, keystore_path=Path(keystore_env))

    dek = envelope.unseal_dek()
    subkeys = derive_subkeys(dek)
    cipher = FieldCipher(subkeys)

    store = EncryptedSessionStore(db_path=db_path, cipher=cipher)
    # Production-wiring regression lock: has_encryption MUST be True.
    assert store.has_encryption is True, (
        "REGRESSION: EncryptedSessionStore.has_encryption is not True -- "
        "encryption wiring silently disabled"
    )
    return store
