"""Production manifest stager — computes real SHA-256 digests + writes manifest.

Run ONCE after downloading the Qwen3-14B OpenVINO model files to stage the
Known-Good Manifest at the configured path.  The manifest is a per-machine
artifact tied to the actual binary files on disk, so it is git-ignored and
regenerated by this command on the deployment host.

Usage::

    python -m shared.models.stage_production_manifest

The command:
  1. Locates the model directory (``models/qwen3-14b/openvino-int4-gpu`` by
     default, matching ``services/.../config/default.toml``).
  2. Computes SHA-256 for every ``*.bin`` file in that directory (reusing
     ``shared.models.weight_integrity.compute_sha256``).
  3. Writes the manifest JSON to the configured path
     (``models/qwen3-14b/openvino-int4-gpu/manifest.json`` by default).

Idempotent: running it again re-hashes and re-writes the manifest.  Safe to
re-run after a model update.

Fail-Closed:
  - If the model directory does not exist → clear error, no partial write.
  - If no ``*.bin`` files are found → clear error, no partial write.
  - If any individual file hash fails → clear error, no partial write.
  - The manifest is written atomically (written to a ``.tmp`` file, then
    renamed so a crash during write does not leave a truncated manifest).

Does NOT sign the manifest.  Signing (FUT-04 / ``require_signed_manifest``)
is out of scope for this helper; set ``require_signed_manifest = false``
(the default) during the ceremony and beyond until the signing ceremony runs.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Final

from shared.models.weight_integrity import compute_sha256

# ---------------------------------------------------------------------------
# Default paths — must match services/.../config/default.toml
# ---------------------------------------------------------------------------

# The model directory and manifest path are hard-coded to the well-known
# production location so the LA does not need to supply any arguments.
# The BLARAI_MODEL_DIR env var provides an override for testing.

_DEFAULT_MODEL_DIR: Final[str] = "models/qwen3-14b/openvino-int4-gpu"
_MANIFEST_FILENAME: Final[str] = "manifest.json"
_MANIFEST_VERSION: Final[str] = "1.0.0"

# FUT-05 / #107 + #917 — the ENFORCED speculative-decoding DRAFT model dirs (flat
# layout, top-dir *.bin): both served drafts, each verified by a real code path and
# signed by the ceremony. ``--drafts`` re-stages them so the signing ceremony has a
# single documented staging command.
#   - qwen3-0.6b-pruned-6l/openvino-int8-gpu — shared-pipeline draft (#107).
#   - qwen3-0.6b/openvino-int4-gpu — PA standalone/fallback draft (#917).
# Deliberately excluded: qwen2.5-1.5b (not a served model at all).
_DRAFT_MODEL_DIRS: Final[tuple[str, ...]] = (
    "models/qwen3-0.6b-pruned-6l/openvino-int8-gpu",
    "models/qwen3-0.6b/openvino-int4-gpu",
)


def _model_dir() -> Path:
    override = os.environ.get("BLARAI_MODEL_DIR", "")
    if override:
        return Path(override)
    return Path(_DEFAULT_MODEL_DIR)


def _manifest_path(model_dir: Path) -> Path:
    override = os.environ.get("BLARAI_MANIFEST_PATH", "")
    if override:
        return Path(override)
    return model_dir / _MANIFEST_FILENAME


# ---------------------------------------------------------------------------
# Visual helpers
# ---------------------------------------------------------------------------


def _header(title: str) -> None:
    width = 70
    print()
    print("=" * width)
    print(f"  {title}")
    print("=" * width)
    print()


def _section(label: str) -> None:
    print(f"\n--- {label} ---")


# ---------------------------------------------------------------------------
# Core logic
# ---------------------------------------------------------------------------


def stage_manifest(
    model_dir: Path,
    manifest_path: Path,
) -> int:
    """Hash every .bin in ``model_dir`` and write the manifest to ``manifest_path``.

    Returns 0 on success, 1 on any failure (Fail-Closed — no partial write).
    """
    _header("BlarAI Production Manifest Stager")

    # ── Step 1: Validate model directory ────────────────────────────────────
    _section("Step 1 of 3 — Locate model files")
    print(f"  Model directory : {model_dir}")

    if not model_dir.exists():
        print(
            f"\nFAIL-CLOSED: model directory not found:\n  {model_dir}\n\n"
            "Check that the Qwen3-14B model has been downloaded to the\n"
            "correct location, then re-run this command.\n"
            "Expected layout:\n"
            f"  {model_dir}/\n"
            "    openvino_model.bin\n"
            "    openvino_tokenizer.bin\n"
            "    openvino_detokenizer.bin\n"
            "    (other model files)\n",
            file=sys.stderr,
        )
        return 1

    bin_files = sorted(model_dir.glob("*.bin"))
    if not bin_files:
        print(
            f"\nFAIL-CLOSED: no .bin files found in:\n  {model_dir}\n\n"
            "The model files have not been downloaded or are in a different\n"
            "directory.  Download the Qwen3-14B OpenVINO INT4 model first.\n",
            file=sys.stderr,
        )
        return 1

    print(f"  Found {len(bin_files)} .bin file(s) to hash:")
    for f in bin_files:
        size_mb = f.stat().st_size / (1024 * 1024)
        print(f"    {f.name}  ({size_mb:.1f} MB)")

    # ── Step 2: Compute SHA-256 for each file ─────────────────────────────
    _section("Step 2 of 3 — Compute SHA-256 digests")
    print("  This may take a moment for large model files...")
    print()

    digests: dict[str, str] = {}
    for bin_file in bin_files:
        try:
            digest = compute_sha256(bin_file)
        except OSError as exc:
            print(
                f"\nFAIL-CLOSED: could not read '{bin_file.name}': {exc}\n"
                "No manifest was written.  Check the file permissions and retry.\n",
                file=sys.stderr,
            )
            return 1
        digests[bin_file.name] = digest
        print(f"  {bin_file.name}")
        print(f"    SHA-256: {digest}")

    # ── Step 3: Write manifest atomically ─────────────────────────────────
    _section("Step 3 of 3 — Write manifest")

    manifest_data: dict = {
        "version": _MANIFEST_VERSION,
        "digests": digests,
    }
    manifest_json = json.dumps(manifest_data, indent=2) + "\n"

    # Atomic write: write to a .tmp file, then rename.
    tmp_path = manifest_path.with_suffix(".json.tmp")
    try:
        manifest_path.parent.mkdir(parents=True, exist_ok=True)
        tmp_path.write_text(manifest_json, encoding="utf-8")
        # Use replace() not rename(): on Windows, rename() raises WinError 183
        # if the target already exists; replace() atomically overwrites it.
        tmp_path.replace(manifest_path)
    except OSError as exc:
        # Clean up the .tmp file if it exists.
        try:
            tmp_path.unlink(missing_ok=True)
        except OSError:
            pass
        print(
            f"\nFAIL-CLOSED: could not write manifest to:\n  {manifest_path}\n"
            f"Error: {exc}\n",
            file=sys.stderr,
        )
        return 1

    print(f"  Manifest written : {manifest_path}")
    print(f"  Entries          : {len(digests)} file(s)")

    # ── Summary ─────────────────────────────────────────────────────────────
    _header("Manifest Staged Successfully")
    print(f"  Manifest path  : {manifest_path}")
    print(f"  Digests staged : {len(digests)} .bin file(s)")
    print()
    print("  The production manifest is now ready.  Run the ceremony preflight")
    print("  to confirm it passes the digest check:")
    print()
    print("    python -m shared.security.ceremony_preflight")
    print()
    print("  NOTE: This manifest is per-machine (gitignored).  If you ever")
    print("  update or re-download the model files, re-run this command.")
    print()
    return 0


# ---------------------------------------------------------------------------
# CLI entrypoint
# ---------------------------------------------------------------------------


def stage_manifest_nested(
    model_dir: Path,
    manifest_path: Path,
) -> int:
    """Hash a NESTED (diffusers-OV / SDXL) layout + write a relative-path manifest.

    For UC-010 (ADR-033 / WS1): walks ``model_dir`` recursively and hashes every
    ``.bin`` weight, every OpenVINO ``.xml`` topology file, AND ``model_index.json``,
    keyed by the relative POSIX path (``unet/openvino_model.bin``,
    ``unet/openvino_model.xml``, ``model_index.json``, …). The produced manifest is
    exactly what :func:`shared.models.weight_integrity.verify_all_manifest_entries_nested`
    requires (so a tampered/extra ``.xml`` or ``model_index.json`` is rejected at
    load). Mirrors the flat :func:`stage_manifest` contract (atomic write,
    fail-closed, returns 0/1) but walks subdirs. The flat 14B stager is unaffected.

    Does NOT sign — signing is a SEPARATE provisioning-ceremony step
    (``shared.models.manifest_signer.sign_manifest``), run after this on the box.
    """
    _header("BlarAI Production Manifest Stager (nested / SDXL)")

    _section("Step 1 of 3 — Locate nested model files")
    print(f"  Model directory : {model_dir}")
    if not model_dir.exists():
        print(
            f"\nFAIL-CLOSED: model directory not found:\n  {model_dir}\n\n"
            "Check that the SDXL model has been downloaded to the correct\n"
            "location (the diffusers-OV INT8 layout: unet/ vae_*/ text_encoder*/\n"
            "model_index.json), then re-run this command.\n",
            file=sys.stderr,
        )
        return 1

    swept: set[Path] = set()
    swept.update(model_dir.rglob("*.bin"))
    swept.update(model_dir.rglob("*.xml"))
    swept.update(model_dir.rglob("model_index.json"))
    targets = sorted(swept)
    if not targets:
        print(
            f"\nFAIL-CLOSED: no .bin/.xml/model_index.json found in:\n  {model_dir}\n\n"
            "The model files have not been downloaded or are in a different\n"
            "directory.\n",
            file=sys.stderr,
        )
        return 1

    print(f"  Found {len(targets)} file(s) to hash (.bin + .xml + model_index.json).")

    _section("Step 2 of 3 — Compute SHA-256 digests")
    print("  This may take a moment for large model files...")
    print()
    digests: dict[str, str] = {}
    for f in targets:
        rel = f.relative_to(model_dir).as_posix()
        try:
            digest = compute_sha256(f)
        except OSError as exc:
            print(
                f"\nFAIL-CLOSED: could not read '{rel}': {exc}\n"
                "No manifest was written.\n",
                file=sys.stderr,
            )
            return 1
        digests[rel] = digest
        print(f"  {rel}")
        print(f"    SHA-256: {digest}")

    _section("Step 3 of 3 — Write manifest")
    manifest_data: dict = {"version": _MANIFEST_VERSION, "digests": digests}
    manifest_json = json.dumps(manifest_data, indent=2) + "\n"
    tmp_path = manifest_path.with_suffix(".json.tmp")
    try:
        manifest_path.parent.mkdir(parents=True, exist_ok=True)
        tmp_path.write_text(manifest_json, encoding="utf-8")
        tmp_path.replace(manifest_path)
    except OSError as exc:
        try:
            tmp_path.unlink(missing_ok=True)
        except OSError:
            pass
        print(
            f"\nFAIL-CLOSED: could not write manifest to:\n  {manifest_path}\n"
            f"Error: {exc}\n",
            file=sys.stderr,
        )
        return 1

    print(f"  Manifest written : {manifest_path}")
    print(f"  Entries          : {len(digests)} file(s)")

    _header("Nested Manifest Staged Successfully")
    print(f"  Manifest path  : {manifest_path}")
    print(f"  Digests staged : {len(digests)} file(s) (.bin + .xml + model_index.json)")
    print()
    print("  NEXT (go-live): SIGN this manifest before flipping enabled, with")
    print("  shared.models.manifest_signer.sign_manifest(<this manifest.json>)")
    print("  (writes the .sig + .pub). [image_generation].require_signed_manifest")
    print("  then requires the valid .sig at load (ADR-033 / FUT-04).")
    print()
    print("  NOTE: this manifest is per-machine (gitignored). Re-run after any")
    print("  model update, then re-sign.")
    print()
    return 0


def stage_drafts() -> int:
    """Stage the enforced speculative-decoding DRAFT manifest (FUT-05 / #107).

    Runs the flat :func:`stage_manifest` for each dir in ``_DRAFT_MODEL_DIRS`` that
    is present (the shared-pipeline draft; flat top-dir-``*.bin`` layout). A draft
    that is absent (gitignored / not on this box) is skipped with a note, NOT a
    failure. Returns 0 when every present draft staged cleanly, 1 if any present
    draft failed to stage (fail-closed).
    """
    _header("BlarAI Draft Manifest Stager (FUT-05 / #107)")
    staged = 0
    skipped = 0
    failed = 0
    for rel in _DRAFT_MODEL_DIRS:
        model_dir = Path(rel)
        if not model_dir.exists():
            print(f"  [skip] absent (gitignored / not on this box): {model_dir}")
            skipped += 1
            continue
        manifest_path = model_dir / _MANIFEST_FILENAME
        rc = stage_manifest(model_dir, manifest_path)
        if rc == 0:
            staged += 1
        else:
            failed += 1
    print()
    print(f"  Drafts staged  : {staged}")
    print(f"  Drafts skipped : {skipped} (absent)")
    print(f"  Drafts failed  : {failed}")
    print()
    print("  NEXT: sign the 14B + this draft with the SAME key —")
    print("    python -m shared.security.provision_manifest_signing_key")
    print()
    return 1 if failed else 0


def main(argv: list[str] | None = None) -> int:
    """CLI entrypoint.

    ``--nested`` (or ``BLARAI_MANIFEST_NESTED=1``) stages the diffusers-OV
    (SDXL / UC-010) NESTED layout — hashing nested ``.bin`` + ``.xml`` +
    ``model_index.json`` keyed by relative path. ``--drafts`` stages the enforced
    speculative-decoding DRAFT manifest (shared-pipeline draft; FUT-05 / #107). The
    default is the flat 14B layout (top-dir ``*.bin`` only), unchanged.
    """
    args = list(argv if argv is not None else sys.argv[1:])
    if "--drafts" in args:
        return stage_drafts()
    nested = "--nested" in args or os.environ.get(
        "BLARAI_MANIFEST_NESTED", ""
    ).strip().lower() in ("1", "true", "yes")
    model_dir = _model_dir()
    manifest_path = _manifest_path(model_dir)
    if nested:
        return stage_manifest_nested(model_dir, manifest_path)
    return stage_manifest(model_dir, manifest_path)


if __name__ == "__main__":
    raise SystemExit(main())
