"""Local image generation via OpenVINO GenAI diffusion pipelines (UC-010, ADR-033).

Two modes, both fully local on the Arc 140V iGPU, **no external network**:
  * ``generate_text2image(prompt, ...)``     — text → image (Text2ImagePipeline)
  * ``generate_image2image(image, prompt)``  — image + text → image (Image2ImagePipeline)

Structural clone of :mod:`shared.inference.vlm` — the proven load-on-demand +
**Fail-Soft** + ``unload()`` + ``log_memory`` template. Any failure (model
missing, disabled, GPU OOM, ``openvino_genai`` absent, manifest mismatch, decode
error) returns ``None`` so callers degrade to a clear "generation unavailable"
notice rather than crashing the app.

**Dormant by default (ADR-033).** The capability ships ``enabled=false`` AND the
uncensored SDXL model is gitignored, so :func:`is_available` is False on a clean
checkout and nothing ever loads. Activation is a SEPARATE LA-present go-live
ceremony (operator content attestation → flip ``[image_generation].enabled`` →
live GPU verify), never a runtime decision.

**Memory posture (ADR-033 §memory).** The diffusion model (~4.4 GB INT8) is too
large to co-reside with the always-resident 14B; it loads on demand and is
evicted after every generate (``unload()`` in the caller's ``finally``). GPU
props deliberately OMIT ``MODEL_PRIORITY="HIGH"`` (the 14B keeps priority; the
diffusion model yields). The 14B is NEVER evicted — the AO orchestrates the
*other* resident caches (VLM + embedder + voice) down before a generate
(``entrypoint`` §E). Phase-0 spike (2026-06-16, Arc 140V): 14B core + ~3k KV +
SDXL INT8 + a 1024² generate peaked ~26.0 GB vs the 31.323 GB ceiling (5.3 GB
headroom); SDXL load 18.7 s, 1024² generate 10.7 s.

**Weight integrity (fail-closed).** ``_get_pipe`` verifies every nested
``.bin`` weight against the SHA-256 manifest before construction
(``weight_integrity.verify_all_manifest_entries_nested``); a mismatch refuses
the load. The runtime NEVER fetches weights.

**Output provenance (ADR-033).** Generated bytes are born on-box from an
operator prompt, are display-only, and are NEVER chunked, embedded, indexed, or
fed to any model. This module only produces the PNG bytes; the AO stores them
born-encrypted (``knowledge_bank.store_generated_image``).
"""

from __future__ import annotations

import gc
import io
import logging
import threading
from dataclasses import dataclass
from pathlib import Path

from shared.diagnostics import log_memory

logger = logging.getLogger(__name__)

_REPO_ROOT = Path(__file__).resolve().parents[2]

#: Default model location (diffusers-OV INT8 layout: unet/ text_encoder/
#: text_encoder_2/ vae_decoder/ vae_encoder/ tokenizer*/ scheduler/
#: model_index.json). ``models/`` is gitignored, so the capability ships ABSENT
#: (dormant by structural absence). Overridable from config (model-agnostic
#: ``model_dir`` — a later checkpoint swap is config, not a rewrite).
IMAGE_GEN_MODEL_DIR = (
    _REPO_ROOT / "models" / "sdxl-uncensored" / "openvino-int8-gpu"
)
_DEVICE = "GPU"

#: The two diffusion pipeline kinds this module can hold (one at a time).
KIND_TEXT2IMAGE = "text2image"
KIND_IMAGE2IMAGE = "image2image"

#: Model VARIANTS UC-010 can run (per-REQUEST style; the AO selects one per
#: IMAGE_GEN_REQUEST and configures image_gen for it). ``_get_pipe`` reloads when
#: a different variant becomes resident (one diffusion model at a time).
#:   * ``photoreal-sdxl`` — photoreal (RealVisXL V5.0, /imagine). No adapter.
#:   * ``illustration`` — flat-vector illustration: base SDXL 1.0 + a flat-style
#:     prompt template (applied gateway-side), NO LoRA (/illustrate, #703).
#:   * ``illustration-cartoon`` — cartoon: the SAME base SDXL + the flat-vector
#:     LoRA applied at RUNTIME (ov_genai AdapterConfig, NOT fused — fusing a flat
#:     LoRA into base SDXL collapsed prompt conditioning) (/cartoon, #703).
VARIANT_PHOTOREAL_SDXL = "photoreal-sdxl"
VARIANT_ILLUSTRATION = "illustration"
VARIANT_ILLUSTRATION_CARTOON = "illustration-cartoon"
KNOWN_VARIANTS = frozenset(
    {VARIANT_PHOTOREAL_SDXL, VARIANT_ILLUSTRATION, VARIANT_ILLUSTRATION_CARTOON}
)

#: Hard generation caps (circuit breakers; the resolved config overrides these,
#: but these are the safe ceilings used when no config is supplied — e.g. a
#: direct call in a unit test). A request over a cap is clamped, never honored
#: blindly (GPU-OOM / memory-DoS control, ADR-033 §H).
_DEFAULT_MAX_WIDTH = 1024
_DEFAULT_MAX_HEIGHT = 1024
#: Default denoising steps for a config-less/direct call. The provisioned base
#: RealVisXL V5.0 uses a standard DDIM-family scheduler (NOT a Lightning few-step
#: model), so it needs ~25-40 steps; the resolved config overrides this.
_DEFAULT_STEPS = 25
#: Minimum dimension floor (a degenerate 0/negative size is refused).
_MIN_DIM = 64

#: Default diffusion scheduler (OpenVINO GenAI ``Scheduler.Type`` name; "AUTO" or
#: empty keeps the model's own scheduler). EULER_ANCESTRAL_DISCRETE renders
#: noticeably sharper detail than the base model's DDIM default at the same step
#: count (UC-010 quality tuning, #666). Overridable from
#: ``[image_generation].scheduler``.
_DEFAULT_SCHEDULER = "EULER_ANCESTRAL_DISCRETE"
#: Default classifier-free guidance scale (prompt-adherence / contrast knob; the
#: SDXL sweet spot is ~5-8). Overridable from ``[image_generation].guidance_scale``.
_DEFAULT_GUIDANCE_SCALE = 7.0
#: Default QUALITY negative prompt — steers AWAY from the common artifact failure
#: modes (blur, bad anatomy/hands, watermarks). This is a QUALITY steer ONLY: it
#: carries NO content/subject terms, so it does NOT re-censor the deliberately
#: uncensored model (ADR-033 §content-safety). Overridable (or cleared) from
#: ``[image_generation].negative_prompt``; an explicit per-call negative wins.
DEFAULT_NEGATIVE_PROMPT = (
    "blurry, low quality, worst quality, low resolution, deformed, disfigured, "
    "bad anatomy, malformed limbs, extra limbs, extra fingers, fused fingers, "
    "mutated hands, poorly drawn hands, poorly drawn face, mutation, ugly, "
    "watermark, signature, text, jpeg artifacts, grainy"
)
#: Hires-fix defaults (UC-010 #666): a second pass that upscales the base image
#: and runs a LOW-strength img2img refine, giving small regions (esp. faces) more
#: pixels to resolve. Off by default (config-less safety); the shipped default.toml
#: enables it. ``factor`` = upscale multiple; ``strength`` = i2i denoise (low
#: preserves composition); ``max_edge`` = hard cap on the refined edge — a GPU-OOM
#: circuit breaker, since the refine runs co-resident with the always-on 14B.
_DEFAULT_HIRES_ENABLED = False
_DEFAULT_HIRES_FACTOR = 1.5
_DEFAULT_HIRES_STRENGTH = 0.4
_DEFAULT_HIRES_MAX_EDGE = 1536


@dataclass(frozen=True)
class ImageGenConfig:
    """Resolved image-generation config (ADR-033 §F).

    Injected by the AO so the module honors the SAME flags the launcher resolved
    from ``[image_generation]`` — never re-parses TOML. Defaults keep a direct
    (config-less) call safe and DORMANT (``enabled=False``).
    """

    enabled: bool = False
    model_dir: Path = IMAGE_GEN_MODEL_DIR
    weight_manifest: Path | None = None
    #: Which model VARIANT this config selects (a label; see KNOWN_VARIANTS). The
    #: launcher resolves ``model_dir``/``weight_manifest`` FROM the variant, so
    #: this records the choice for logging + the resident-swap key (a different
    #: variant forces an unload+reload). Default = the live photoreal SDXL, so a
    #: config-less / back-compat call is byte-identical to the pre-variant path.
    model_variant: str = VARIANT_PHOTOREAL_SDXL
    device: str = _DEVICE
    steps: int = _DEFAULT_STEPS
    #: Sampler / quality knobs (UC-010 #666). ``scheduler``: OV GenAI
    #: ``Scheduler.Type`` name ("AUTO"/empty = the model's own scheduler).
    #: ``guidance_scale``: classifier-free guidance (prompt adherence).
    #: ``negative_prompt``: a QUALITY steer (no content terms — the model stays
    #: uncensored); an explicit per-call negative_prompt overrides it.
    scheduler: str = _DEFAULT_SCHEDULER
    guidance_scale: float = _DEFAULT_GUIDANCE_SCALE
    negative_prompt: str = DEFAULT_NEGATIVE_PROMPT
    #: Hires-fix second pass (UC-010 #666): upscale + low-strength img2img refine
    #: for more detail (notably small faces). ``hires_max_edge`` bounds the
    #: refined resolution (GPU-OOM circuit breaker, co-resident with the 14B).
    #: Fail-soft: a refine failure returns the base image.
    hires_enabled: bool = _DEFAULT_HIRES_ENABLED
    hires_factor: float = _DEFAULT_HIRES_FACTOR
    hires_strength: float = _DEFAULT_HIRES_STRENGTH
    hires_max_edge: int = _DEFAULT_HIRES_MAX_EDGE
    max_width: int = _DEFAULT_MAX_WIDTH
    max_height: int = _DEFAULT_MAX_HEIGHT
    idle_unload_s: int = 60
    # FUT-04 parity with the 14B (ADR-018, UC-010 WS1): when True the nested
    # SDXL manifest MUST be present AND carry a valid TPM ``.sig`` or the load
    # refuses fail-closed (no SKIP-with-WARNING). Default False keeps a direct
    # (config-less) / dormant-dev call safe; the AO threads
    # ``[image_generation].require_signed_manifest`` in at start.
    require_signed_manifest: bool = False

    # UC-010 illustration RUNTIME LoRA adapter (#703). When set, the diffusion
    # pipeline is built WITH this LoRA applied at RUNTIME (ov_genai AdapterConfig)
    # — NEVER fused into the weights. Fusing a flat-vector LoRA into base SDXL
    # collapsed prompt conditioning (coherent but prompt-IGNORING output);
    # applying it at runtime preserves conditioning (the cartoon style). None =>
    # no adapter (the flat-vector + photoreal styles). ``alpha`` is the style
    # strength; ``sha256`` (when set) is integrity-verified before load. Fail-Soft:
    # a missing file, a hash mismatch, or any build error degrades to NO adapter,
    # never a hard crash.
    lora_adapter_path: Path | None = None
    lora_adapter_alpha: float = 0.8
    lora_adapter_sha256: str = ""


#: Module-global resident pipeline state (mirrors ``vlm.py`` — one pipeline
#: cached behind a lock; ``_model_kind`` records which kind is resident so
#: loading a different kind unloads the prior one first).
_pipe = None
_model_kind: str | None = None
#: Which model variant is currently resident (``None`` when no pipe is loaded).
#: A configured variant that differs from this forces an unload+reload in
#: ``_get_pipe`` — one diffusion model resident at a time, across variants too.
_model_variant: str | None = None
_lock = threading.Lock()
_load_failed = False

#: The active resolved config. ``configure()`` sets it at AO start; a None
#: config resolves to the DORMANT default (``enabled=False``) so an
#: un-configured process can never load a model.
_config: ImageGenConfig = ImageGenConfig()


def configure(config: ImageGenConfig) -> None:
    """Install the resolved image-gen config (called once at AO start, ADR-033 §E/§F).

    Idempotent and thread-safe. Changing ``model_dir``/``device`` while a
    pipeline is resident does NOT hot-swap it — the next ``unload()`` + load
    picks up the new config (the AO unloads after every generate, so this is the
    normal path). Mirrors how ``vlm`` uses module constants, but config-injected
    so the dormancy gate is driven by the launcher-resolved TOML flag.
    """
    global _config
    with _lock:
        _config = config
    logger.info(
        "image_gen configured: enabled=%s variant=%s model_dir=%s device=%s "
        "steps=%d scheduler=%s guidance_scale=%.1f neg_prompt_len=%d "
        "hires=%s(f%.2f s%.2f max_edge=%d) max=%dx%d "
        "idle_unload_s=%d require_signed_manifest=%s",
        config.enabled,
        config.model_variant,
        config.model_dir,
        config.device,
        config.steps,
        config.scheduler,
        config.guidance_scale,
        len(config.negative_prompt or ""),
        config.hires_enabled,
        config.hires_factor,
        config.hires_strength,
        config.hires_max_edge,
        config.max_width,
        config.max_height,
        config.idle_unload_s,
        config.require_signed_manifest,
    )


def current_config() -> ImageGenConfig:
    """The currently installed resolved config (DORMANT default if unset)."""
    return _config


def _model_present(model_dir: Path) -> bool:
    """True iff the diffusers-OV model layout is on disk (model_index.json +
    the unet weight). Cheap structural check — NOT a manifest verify (that runs
    at load time, fail-closed)."""
    return (
        (model_dir / "model_index.json").exists()
        and (model_dir / "unet" / "openvino_model.xml").exists()
        and (model_dir / "unet" / "openvino_model.bin").exists()
    )


def is_available() -> bool:
    """True iff image generation is ENABLED, the model is on disk, and
    ``openvino_genai`` is importable.

    DORMANCY INVARIANT (ADR-033): returns False when ``enabled=False`` (the
    shipped default) OR the model is absent (the gitignored-by-structural-
    absence default) OR ``openvino_genai`` is missing — so ``/imagine`` and the
    ``generate_image`` tool degrade to a clear notice with NO load attempted.
    """
    cfg = _config
    if not cfg.enabled:
        return False
    if not _model_present(cfg.model_dir):
        return False
    try:
        import openvino_genai  # noqa: F401
    except ImportError:
        return False
    return True


def _gpu_properties(device: str) -> dict[str, object]:
    """GPU compile properties for the diffusion pipeline (ADR-033 §A).

    Mirrors ``shared_pipeline.build_shared_pipeline`` (PERFORMANCE_HINT=LATENCY,
    INFERENCE_PRECISION_HINT=f16, GPU_ENABLE_SDPA_OPTIMIZATION=ON, CACHE_DIR="")
    but DELIBERATELY OMITS ``MODEL_PRIORITY="HIGH"``: the diffusion model yields
    to the always-resident 14B under memory pressure, never the reverse. Only
    used for GPU; a non-GPU device passes no GPU-specific props.
    """
    if device.upper() != "GPU":
        return {}
    return {
        "PERFORMANCE_HINT": "LATENCY",
        "INFERENCE_PRECISION_HINT": "f16",
        "GPU_ENABLE_SDPA_OPTIMIZATION": "ON",
        "CACHE_DIR": "",
    }


def _build_scheduler(cfg: ImageGenConfig):
    """Build the configured diffusion scheduler, or None to use the model default.

    The provisioned base SDXL ships a DDIM ``scheduler_config.json``;
    EULER_ANCESTRAL_DISCRETE / EULER_DISCRETE generally render sharper detail at
    the same step count (UC-010 quality tuning, #666). The choice is
    ``[image_generation].scheduler`` (case-insensitive; "AUTO"/empty keeps the
    model default).

    Fail-soft: an unknown ``Scheduler.Type`` name, a missing
    ``scheduler_config.json``, or any construction error logs a WARNING and
    returns None — the pipeline then uses the model's OWN scheduler, never a hard
    failure (mirrors the module-wide Fail-Soft posture).
    """
    name = (cfg.scheduler or "").strip().upper()
    if not name or name == "AUTO":
        return None
    try:
        import openvino_genai as ov_genai

        stype = getattr(ov_genai.Scheduler.Type, name, None)
        if stype is None:
            logger.warning(
                "image_gen: unknown scheduler %r — using the model default. "
                "Valid types: %s",
                cfg.scheduler,
                [t for t in dir(ov_genai.Scheduler.Type) if t.isupper()],
            )
            return None
        cfg_path = cfg.model_dir / "scheduler" / "scheduler_config.json"
        if not cfg_path.exists():
            logger.warning(
                "image_gen: %s not found — using the model default scheduler.",
                cfg_path,
            )
            return None
        scheduler = ov_genai.Scheduler.from_config(str(cfg_path), stype)
        logger.info("image_gen: using %s scheduler.", name)
        return scheduler
    except Exception as exc:  # noqa: BLE001 — Fail-Soft: bad scheduler -> model default
        logger.warning(
            "image_gen: scheduler build failed (%s) — using the model default.",
            exc,
        )
        return None


def _verify_weights(cfg: ImageGenConfig) -> bool:
    """Verify the model's nested weights + topology against the SHA-256 manifest.

    Coverage (UC-010 WS1): every nested ``.bin`` weight AND every OpenVINO
    ``.xml`` topology file AND ``model_index.json`` is hashed + required, and any
    extra/unlisted one is rejected — so a write-capable actor cannot swap the
    compute graph past a ``.bin``-only digest list.

    Signature (FUT-04 parity with the 14B): when ``cfg.require_signed_manifest``
    is True the nested verify goes through ``load_manifest_verified`` — the
    manifest MUST carry a valid TPM ``.sig`` or the load refuses fail-closed.

    Fail-closed: returns False (the load then refuses) when verification fails
    for ANY entry, the manifest path is missing, the signature is missing/invalid
    under ``require_signed_manifest``, OR ``require_signed_manifest`` is True but
    no ``weight_manifest`` is configured (a go-live misconfiguration — you cannot
    sign-verify a manifest that does not exist). Only when
    ``require_signed_manifest`` is False AND ``weight_manifest`` is None is the
    check SKIPPED with a WARNING (the dormant-dev posture, never silent). The
    runtime NEVER fetches weights.
    """
    manifest = cfg.weight_manifest
    if manifest is None:
        if cfg.require_signed_manifest:
            logger.error(
                "image_gen: require_signed_manifest=true but no weight_manifest "
                "is configured — refusing to load the diffusion model "
                "(Fail-Closed). Run the provisioning ceremony to stage + sign "
                "the manifest before go-live (ADR-033 §F / FUT-04)."
            )
            return False
        logger.warning(
            "image_gen: no weight_manifest configured — SKIPPING weight "
            "integrity verification (require_signed_manifest=false). Run the "
            "provisioning ceremony to generate + sign the manifest before "
            "go-live (ADR-033 §F)."
        )
        return True
    # Nested-layout verify (diffusers-OV puts .bin/.xml files in subdirs). Reuses
    # the proven primitives (load_manifest[_verified] + compute_sha256) via the
    # nested sibling of verify_all_manifest_entries — the flat function globs
    # *.bin in the top dir only and keys by bare name, which collides on SDXL's
    # repeated 'openvino_model.bin'. require_signed routes the load through
    # load_manifest_verified (TPM .sig gate). See
    # weight_integrity.verify_all_manifest_entries_nested.
    from shared.models.weight_integrity import verify_all_manifest_entries_nested

    result = verify_all_manifest_entries_nested(
        cfg.model_dir,
        manifest,
        require_signed=cfg.require_signed_manifest,
    )
    if not result.all_verified:
        logger.error(
            "image_gen: weight integrity FAILED (%s) — refusing to load the "
            "diffusion model (Fail-Closed).",
            result.error,
        )
        return False
    logger.info(
        "image_gen: weight integrity verified (%d nested entries, "
        "require_signed=%s).",
        len(result.per_file),
        cfg.require_signed_manifest,
    )
    return True


def _build_adapter_config(cfg: ImageGenConfig):
    """Build an ov_genai ``AdapterConfig`` for a RUNTIME LoRA, or None (#703).

    Returns None (no adapter — the flat-vector + photoreal styles) when no
    ``lora_adapter_path`` is configured. Applies the LoRA at RUNTIME, NEVER fused
    (fusing a flat-vector LoRA into base SDXL collapsed prompt conditioning — the
    model produced coherent but prompt-ignoring images; the runtime adapter
    preserves conditioning). Fail-Soft / fail-closed-on-integrity: a missing
    file, a SHA-256 mismatch (when ``lora_adapter_sha256`` is set), or any build
    error logs and returns None so generation still produces an image WITHOUT the
    style adapter rather than crashing. Under ``require_signed_manifest`` the pin
    is MANDATORY — an UNPINNED adapter is refused (the LoRA sits outside the
    signed model_dir, so the pin is its sole integrity control; #703)."""
    raw = cfg.lora_adapter_path
    if not raw:
        return None
    path = Path(raw)
    if not path.exists():
        logger.warning(
            "image_gen: LoRA adapter %s not found — generating WITHOUT the style "
            "adapter (Fail-Soft).", path,
        )
        return None
    # #703 hardening (review MINOR #1): the LoRA lives OUTSIDE the signed
    # model_dir, so its SHA-256 pin is its SOLE integrity control. Under
    # require_signed_manifest the pin is therefore MANDATORY — refuse an
    # UNPINNED adapter (fail-soft to no-adapter) rather than silently apply an
    # unverified weight, so the LoRA can never be the one weight whose
    # verification is config-switched-off in a signed-manifest deployment.
    if cfg.require_signed_manifest and not cfg.lora_adapter_sha256.strip():
        logger.error(
            "image_gen: LoRA adapter %s has NO sha256 pin under "
            "require_signed_manifest — refusing the adapter (integrity; "
            "fail-soft to no-adapter). Set lora_adapter_sha256 to enable it.",
            path.name,
        )
        return None
    if cfg.lora_adapter_sha256:
        try:
            import hashlib

            h = hashlib.sha256()
            with open(path, "rb") as fh:
                for chunk in iter(lambda: fh.read(1 << 20), b""):
                    h.update(chunk)
            actual = h.hexdigest()
        except Exception as exc:  # noqa: BLE001 — cannot hash -> refuse adapter
            logger.warning(
                "image_gen: could not hash LoRA adapter %s (%s) — refusing the "
                "adapter (integrity).", path, exc,
            )
            return None
        if actual.lower() != cfg.lora_adapter_sha256.strip().lower():
            logger.error(
                "image_gen: LoRA adapter %s SHA-256 mismatch — refusing the "
                "adapter (integrity). expected=%s actual=%s",
                path.name, cfg.lora_adapter_sha256, actual,
            )
            return None
    try:
        import openvino_genai as ov_genai

        adapter = ov_genai.Adapter(str(path))
        acfg = ov_genai.AdapterConfig()
        acfg.add(adapter, float(cfg.lora_adapter_alpha))
        logger.info(
            "image_gen: runtime LoRA adapter %s (alpha=%.2f) applied (not fused).",
            path.name, cfg.lora_adapter_alpha,
        )
        return acfg
    except Exception as exc:  # noqa: BLE001 — Fail-Soft: degrade to no adapter
        logger.warning(
            "image_gen: building the LoRA adapter failed (%s) — generating "
            "WITHOUT it (Fail-Soft).", exc,
        )
        return None


def _construct_pipe(ctor, cfg: ImageGenConfig, props: dict, scheduler, adapters=None):
    """Construct + compile one diffusion pipeline; return it, or None (Fail-Soft).

    With a custom *scheduler*: construct UNCOMPILED (the path-only ctor), install
    the scheduler via ``set_scheduler``, then ``compile`` to the device. A
    ``Scheduler`` is NOT a valid constructor property (the ctor ``**kwargs`` are
    an OpenVINO ``AnyMap``), so set_scheduler-before-compile is the ONLY supported
    path (OV GenAI 2026.1; passing ``scheduler=`` to the ctor raises). Without a
    scheduler: the combined construct+compile ctor. Both retry without the GPU
    hint kwargs on a ``TypeError`` (older-build fallback). Any other construction
    error returns None so the caller can degrade (e.g. retry with the model
    default scheduler).

    *adapters* (an ov_genai ``AdapterConfig`` or None) applies a RUNTIME LoRA
    without fusing it into the weights (UC-010 cartoon style, #703). Verified to
    compose with a custom scheduler via ``compile(device, adapters=...)``. On a
    ``TypeError`` fallback the GPU hint kwargs are dropped but the adapters are
    KEPT (the adapter is the point of the cartoon style, never a quality nicety)."""
    def _kw(base: dict) -> dict:
        kw = dict(base)
        if adapters is not None:
            kw["adapters"] = adapters
        return kw

    try:
        if scheduler is not None:
            pipe = ctor(str(cfg.model_dir))
            pipe.set_scheduler(scheduler)
            try:
                pipe.compile(cfg.device, **_kw(props))
            except TypeError as exc:
                logger.warning(
                    "image_gen: compile rejected GPU kwargs (older OV GenAI "
                    "build) — retrying without hints. Reason: %s", exc,
                )
                pipe.compile(cfg.device, **_kw({}))
            return pipe
        try:
            return ctor(str(cfg.model_dir), cfg.device, **_kw(props))
        except TypeError as exc:
            logger.warning(
                "image_gen: pipeline rejected GPU kwargs (older OV GenAI build) "
                "— retrying without hints. Reason: %s", exc,
            )
            return ctor(str(cfg.model_dir), cfg.device, **_kw({}))
    except Exception as exc:  # noqa: BLE001 — Fail-Soft: caller degrades/retries
        logger.error("image_gen: pipeline construction failed: %s", exc)
        return None


def _get_pipe(kind: str):
    """Lazily load + cache the diffusion pipeline of *kind* on the GPU.

    Returns None on any failure (Fail-Soft). Loading a DIFFERENT kind than the
    one resident unloads the prior pipeline first (one diffusion pipeline
    resident at a time — the memory budget does not hold two). Verifies weights
    fail-closed before construction.
    """
    global _pipe, _model_kind, _model_variant, _load_failed
    cfg = _config
    if (
        _pipe is not None
        and _model_kind == kind
        and _model_variant == cfg.model_variant
    ):
        return _pipe
    if _load_failed:
        return None
    with _lock:
        # Re-check under the lock (another thread may have loaded/failed).
        if (
            _pipe is not None
            and _model_kind == kind
            and _model_variant == cfg.model_variant
        ):
            return _pipe
        if _load_failed:
            return None
        # A resident pipeline of the WRONG kind OR a DIFFERENT model variant must
        # be dropped first — the budget holds one diffusion model, not two (and
        # not two variants). Drop the reference and reclaim before loading the
        # new one (no recursive unload() call — we already hold the lock).
        if _pipe is not None and (
            _model_kind != kind or _model_variant != cfg.model_variant
        ):
            logger.info(
                "image_gen: swapping diffusion model %s/%s -> %s/%s (one "
                "resident at a time)",
                _model_variant, _model_kind, cfg.model_variant, kind,
            )
            _pipe = None
            _model_kind = None
            _model_variant = None
            gc.collect()
        if not _verify_weights(cfg):
            _load_failed = True
            return None
        try:
            import openvino_genai as ov_genai

            log_memory(logger, "image_gen.load.before", kind=kind)
            logger.info(
                "Loading diffusion pipeline (%s, %s) on %s",
                cfg.model_dir.name, kind, cfg.device,
            )
            props = _gpu_properties(cfg.device)
            ctor = (
                ov_genai.Text2ImagePipeline
                if kind == KIND_TEXT2IMAGE
                else ov_genai.Image2ImagePipeline
            )
            # Resolve the configured scheduler (Fail-Soft: None => model default)
            # and the optional RUNTIME LoRA adapter (#703; None for flat/photoreal).
            scheduler = _build_scheduler(cfg)
            adapters = _build_adapter_config(cfg)
            pipe = _construct_pipe(ctor, cfg, props, scheduler, adapters)
            if pipe is None and scheduler is not None:
                # A custom scheduler broke construction — it is a QUALITY
                # enhancement, never a generation blocker. Retry once with the
                # model's default scheduler so an image still comes out (KEEP the
                # adapter — it is the cartoon style, not a nicety).
                logger.warning(
                    "image_gen: construction with the %s scheduler failed — "
                    "retrying with the model's default scheduler.",
                    cfg.scheduler,
                )
                pipe = _construct_pipe(ctor, cfg, props, None, adapters)
            if pipe is None:
                _load_failed = True
                return None
            _pipe = pipe
            _model_kind = kind
            _model_variant = cfg.model_variant
            log_memory(logger, "image_gen.load.after", kind=kind)
            logger.info("Diffusion pipeline loaded (%s).", kind)
            return _pipe
        except Exception as exc:  # noqa: BLE001 — Fail-Soft: any load failure degrades
            logger.error(
                "image_gen load failed; generation degrades to unavailable: %s",
                exc,
            )
            _load_failed = True
            return None


def _clamp_dims(
    width: int,
    height: int,
    cfg: ImageGenConfig,
    max_w: int | None = None,
    max_h: int | None = None,
) -> tuple[int, int]:
    """Clamp requested dimensions into ``[_MIN_DIM, max_*]`` (circuit breaker).

    A request over the cap is CLAMPED to the cap (never honored blindly — the
    GPU-OOM/memory-DoS control, ADR-033 §H); a degenerate zero/negative size
    floors to ``_MIN_DIM``. Rounded down to a multiple of 8 (SDXL latent stride)
    so the pipeline never rejects an odd size. *max_w*/*max_h* override the
    config caps — used by the hires-fix refine, which deliberately exceeds the
    base ``max_width``/``max_height`` up to ``hires_max_edge``.
    """
    mw = max_w if max_w is not None else cfg.max_width
    mh = max_h if max_h is not None else cfg.max_height
    w = max(_MIN_DIM, min(int(width), mw))
    h = max(_MIN_DIM, min(int(height), mh))
    w -= w % 8
    h -= h % 8
    return w, h


def _resolve_steps(steps: int | None, cfg: ImageGenConfig) -> int:
    """Resolve the effective denoising-step count for a generate call.

    A NON-POSITIVE *steps* (``None`` OR ``0``) means "use the configured
    ``[image_generation].steps`` default" — it is NOT a request for a literal
    zero/one-step run. This matters because the gateway ``ImagineCoordinator``
    and the ``IMAGE_GEN_REQUEST`` frame default ``steps`` to ``0`` ("operator
    gave no override; the AO decides"), and the AO forwards that ``0`` here. The
    prior ``steps is not None`` check let the ``0`` through and ``max(1, 0)``
    floored every generation to a SINGLE denoising step — which yields pure
    noise on a base (non-Lightning) SDXL regardless of the configured step count
    (#666 go-live: ``steps=30`` in config but every request carried 0 -> 1 step
    -> noise). Always returns at least 1 (a config of 0 floors to 1).
    """
    n = int(steps) if (steps is not None and steps > 0) else cfg.steps
    return max(1, int(n))


def _tensor_to_png_bytes(tensor) -> bytes | None:
    """Encode an OpenVINO image Tensor (1×H×W×C or H×W×C uint8) to PNG bytes."""
    try:
        import numpy as np
        from PIL import Image

        arr = np.array(tensor.data if hasattr(tensor, "data") else tensor)
        # GenAI returns a batched NHWC tensor; take the first image.
        if arr.ndim == 4:
            arr = arr[0]
        if arr.dtype != np.uint8:
            arr = arr.astype(np.uint8)
        img = Image.fromarray(arr, mode="RGB")
        buf = io.BytesIO()
        img.save(buf, format="PNG")
        return buf.getvalue()
    except Exception as exc:  # noqa: BLE001 — Fail-Soft
        logger.error("image_gen: PNG encode failed: %s", exc)
        return None


def _upscale_png(png_bytes: bytes, factor: float, max_edge: int) -> bytes | None:
    """Upscale PNG bytes by *factor* (capped at *max_edge*, multiple of 8) via
    Lanczos. Returns the new PNG bytes (or the original if no upscale is needed),
    or None on failure (Fail-Soft). Pure CPU resample — no model."""
    try:
        from PIL import Image

        img = Image.open(io.BytesIO(png_bytes)).convert("RGB")
        w, h = img.size
        tw = min(int(round(w * factor)), max_edge)
        th = min(int(round(h * factor)), max_edge)
        tw = max(_MIN_DIM, tw - (tw % 8))
        th = max(_MIN_DIM, th - (th % 8))
        if (tw, th) == (w, h):
            return png_bytes
        up = img.resize((tw, th), Image.LANCZOS)
        buf = io.BytesIO()
        up.save(buf, format="PNG")
        return buf.getvalue()
    except Exception as exc:  # noqa: BLE001 — Fail-Soft
        logger.warning(
            "image_gen: hires upscale failed (%s) — skipping refine.", exc
        )
        return None


def _hires_refine(
    base_png: bytes,
    prompt: str,
    cfg: ImageGenConfig,
    negative_prompt: str,
    seed: int | None,
) -> bytes | None:
    """Hires-fix second pass: upscale the base image, then a LOW-strength
    img2img refine so small regions (esp. faces) gain real detail without
    changing composition.

    Reuses :func:`generate_image2image` (which kind-swaps to the i2i pipeline)
    with the dimension cap raised to ``cfg.hires_max_edge``. Fail-soft: any
    failure — the upscale, the i2i load/generate, or a GPU-OOM at the higher
    resolution — returns None so the caller keeps the base image. Hires is an
    enhancement, never a generation blocker."""
    upscaled = _upscale_png(base_png, cfg.hires_factor, cfg.hires_max_edge)
    if upscaled is None:
        return None
    logger.info(
        "image_gen: hires-fix refine (factor=%.2f strength=%.2f max_edge=%d)",
        cfg.hires_factor, cfg.hires_strength, cfg.hires_max_edge,
    )
    return generate_image2image(
        upscaled,
        prompt,
        strength=cfg.hires_strength,
        steps=cfg.steps,
        seed=seed,
        negative_prompt=negative_prompt,
        max_edge=cfg.hires_max_edge,
    )


def generate_text2image(
    prompt: str,
    *,
    width: int = _DEFAULT_MAX_WIDTH,
    height: int = _DEFAULT_MAX_HEIGHT,
    steps: int | None = None,
    seed: int | None = None,
    negative_prompt: str = "",
) -> bytes | None:
    """Generate a PNG image from *prompt*; return its bytes, or None (Fail-Soft).

    Returns None when image generation is unavailable (disabled, model absent,
    ``openvino_genai`` missing, or any load/generate/encode failure) so the
    caller emits a clear "generation unavailable" notice. Dimensions are clamped
    to the configured caps (circuit breaker). Generation is serialised under the
    module lock (one GPU pipeline; the AO is blocked for the generate window —
    a named UX cost, ADR-033).

    Args:
        prompt: The text prompt. An empty prompt returns None (nothing to do).
        width/height: Requested pixel dimensions (clamped to caps).
        steps: Inference steps (defaults to the configured ``steps``).
        seed: Optional RNG seed for reproducibility.
        negative_prompt: Optional negative prompt.
    """
    if not is_available():
        return None
    if not prompt or not prompt.strip():
        return None
    pipe = _get_pipe(KIND_TEXT2IMAGE)
    if pipe is None:
        return None
    cfg = _config
    w, h = _clamp_dims(width, height, cfg)
    n_steps = _resolve_steps(steps, cfg)
    try:
        import openvino_genai as ov_genai

        gen_kwargs: dict[str, object] = {
            "width": w,
            "height": h,
            "num_inference_steps": max(1, n_steps),
            "num_images_per_prompt": 1,
            "guidance_scale": float(cfg.guidance_scale),
        }
        # A per-call negative_prompt wins; otherwise the configured QUALITY
        # default negative applies (artifact/anatomy steer, not a content filter).
        neg = negative_prompt.strip() or (cfg.negative_prompt or "").strip()
        if neg:
            gen_kwargs["negative_prompt"] = neg
        if seed is not None:
            gen_kwargs["rng_seed"] = int(seed)
        log_memory(logger, "image_gen.t2i.before", dims=f"{w}x{h}", steps=n_steps)
        # Pipeline is not concurrency-safe; serialise generate (and the lazy
        # load). The lock blocks the AO for the generate window.
        with _lock:
            # Re-assert UNDER the lock that the resident pipe is still present
            # AND of the expected kind — _get_pipe released the lock between the
            # load and here, so a concurrent kind-swap (or unload) must not let a
            # t2i request run on an i2i pipeline. Fail-Soft to None on a mismatch.
            if _pipe is None or _model_kind != KIND_TEXT2IMAGE:
                return None
            result = _pipe.generate(prompt, **gen_kwargs)
        log_memory(logger, "image_gen.t2i.after", dims=f"{w}x{h}", steps=n_steps)
        base_png = _tensor_to_png_bytes(result)
        if base_png is None or not cfg.hires_enabled:
            return base_png
        # Hires-fix second pass (the _lock above is released, so the i2i refine
        # can re-acquire it without deadlock): upscale + a low-strength img2img
        # refine for more detail, especially small faces. Fail-soft — a refine
        # failure (incl. GPU-OOM at the higher resolution) keeps the base image.
        refined = _hires_refine(base_png, prompt, cfg, negative_prompt, seed)
        return refined if refined is not None else base_png
    except Exception as exc:  # noqa: BLE001 — Fail-Soft
        logger.error("image_gen generate_text2image failed: %s", exc)
        return None
    finally:
        del ov_genai


def generate_image2image(
    image_bytes: bytes,
    prompt: str,
    *,
    strength: float = 0.65,
    steps: int | None = None,
    seed: int | None = None,
    negative_prompt: str = "",
    max_edge: int | None = None,
) -> bytes | None:
    """Generate a PNG image conditioned on an input image + *prompt* (img2img).

    *image_bytes* is the LOCAL seed image (a stored ``blarai-img://`` decode or
    an operator-named local file — NEVER a URL; no egress). Returns None on any
    failure (Fail-Soft). ``strength`` controls how far the result departs from
    the seed (0=identity, 1=ignore the seed). Dimensions follow the seed image
    but are clamped to the configured caps.

    Args:
        image_bytes: Raw bytes of the seed image (PNG/JPEG/WebP).
        prompt: The text prompt steering the edit.
        strength: img2img strength in [0, 1].
        steps: Inference steps (defaults to the configured ``steps``).
        seed: Optional RNG seed.
        negative_prompt: Optional negative prompt.
    """
    if not is_available():
        return None
    if not prompt or not prompt.strip():
        return None
    if not image_bytes:
        return None
    pipe = _get_pipe(KIND_IMAGE2IMAGE)
    if pipe is None:
        return None
    cfg = _config
    try:
        import numpy as np
        import openvino as ov
        import openvino_genai as ov_genai  # noqa: F401  (presence already proven)
        from PIL import Image

        seed_img = Image.open(io.BytesIO(image_bytes)).convert("RGB")
        # max_edge overrides the base caps: the hires-fix refine passes
        # hires_max_edge so it can exceed max_width/max_height; None keeps caps.
        w, h = _clamp_dims(
            seed_img.width, seed_img.height, cfg, max_w=max_edge, max_h=max_edge
        )
        if (w, h) != seed_img.size:
            seed_img = seed_img.resize((w, h))
        tensor = ov.Tensor(np.expand_dims(np.array(seed_img), axis=0))
        n_steps = _resolve_steps(steps, cfg)
        gen_kwargs: dict[str, object] = {
            "image": tensor,
            "strength": float(max(0.0, min(1.0, strength))),
            "num_inference_steps": max(1, n_steps),
            "num_images_per_prompt": 1,
            "guidance_scale": float(cfg.guidance_scale),
        }
        neg = negative_prompt.strip() or (cfg.negative_prompt or "").strip()
        if neg:
            gen_kwargs["negative_prompt"] = neg
        if seed is not None:
            gen_kwargs["rng_seed"] = int(seed)
        log_memory(logger, "image_gen.i2i.before", dims=f"{w}x{h}", steps=n_steps)
        with _lock:
            # Re-assert pipe presence AND kind under the lock (see
            # generate_text2image) — a concurrent kind-swap/unload must not run
            # an i2i request on a t2i pipeline. Fail-Soft to None on a mismatch.
            if _pipe is None or _model_kind != KIND_IMAGE2IMAGE:
                return None
            result = _pipe.generate(prompt, **gen_kwargs)
        log_memory(logger, "image_gen.i2i.after", dims=f"{w}x{h}", steps=n_steps)
        return _tensor_to_png_bytes(result)
    except Exception as exc:  # noqa: BLE001 — Fail-Soft
        logger.error("image_gen generate_image2image failed: %s", exc)
        return None


def unload() -> None:
    """Release the cached diffusion pipeline and free its ~4.4 GB. Idempotent, Fail-Soft.

    Mirrors ``vlm.unload()``: drop the reference under ``_lock``, reset
    ``_load_failed`` (so a later request re-loads cleanly), ``gc.collect()`` to
    force prompt reclamation, and report what the OS actually reclaimed (honest
    accounting — on this runtime the driver may pool native GPU/system memory
    intra-process, so the before/after numbers tell the truth). The caller
    ``unload()``s in a ``finally`` after every generate; the resident 14B is
    NEVER touched here.
    """
    global _pipe, _model_kind, _model_variant, _load_failed
    with _lock:
        already_clear = _pipe is None and not _load_failed
        _pipe = None
        _model_kind = None
        _model_variant = None
        _load_failed = False
    if already_clear:
        return
    before = log_memory(logger, "image_gen.unload.before")
    gc.collect()
    after = log_memory(logger, "image_gen.unload.after")
    if before and after:
        freed = after.get("sys_available_mb", 0.0) - before.get(
            "sys_available_mb", 0.0
        )
        logger.info(
            "Diffusion pipeline dereferenced + gc; system available %+.0fMB "
            "(native GPU memory may be driver-pooled).", freed,
        )
    else:
        logger.info("Diffusion pipeline dereferenced + gc.")
